sparrowapp-dev/sparrow-app

apps/@sparrow-storybook/src/stories/Color/Color.docs.mdx
apps/@sparrow-storybook/src/stories/Iconography/Iconography.docs.mdx
apps/@sparrow-storybook/src/stories/Layout/Layout.docs.mdx
apps/@sparrow-storybook/src/stories/Logos/Logos.docs.mdx

fix: ui & content fix in storybook []

---

apps/@sparrow-storybook/src/stories/Shadow/Shadow.docs.mdx
apps/@sparrow-storybook/src/stories/Spacing/Spacing.docs.mdx
apps/@sparrow-storybook/src/stories/Typography/Typography.docs.mdx

fix: storybook fixes []

---

apps/@sparrow-storybook/src/stories/Typography/Typography.docs.mdx

fix: updated the import path for the typography []

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: upgrade sparrow version to v2.16.0 []

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts

Argument sync fixed when changing query.

fix: query to editor sync

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/utils/decode-request.ts

fix: fixed environemnt issue in form data and url encoded []

---

packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte

Please do not leave this blank 
- [x ] 🐛 Bug Fix
- [x ] 👍 yes
- [ x] 🙅 no, because they aren't needed

fixed ui issue

---

packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte

Dummy PR for deployment of dev code on dev branch.

fix: added env []

---

packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte
packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte

DS - Side navigation rails
[#2462](https://github.com/sparrowapp-dev/sparrow-app/issues/2462)
completed

DS - Side navigation rails #2462

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte

fix: workspace switch []

---

packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte

fix: side navigation
DS - Side navigation rails
[#2462](https://github.com/sparrowapp-dev/sparrow-app/issues/2462)

fix: side navigation

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
packages/@sparrow-common/src/components/switch-workspace/SwitchWorkspace.svelte

added variable to destroy collection page in case of workspace switching

fix: added variable to destroy collection page in case of workspace switching []

---

packages/@sparrow-common/src/components/global-search/sub-components/SearchBar.svelte

fix: fixed styling issues []

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-desktop/src/repositories/environment.repository.ts
apps/@sparrow-desktop/src/repositories/testflow.repository.ts
apps/@sparrow-desktop/src/repositories/workspace.repository.ts
packages/@sparrow-common/src/components/SearchBar/SearchBar.svelte
packages/@sparrow-common/src/components/global-search/GlobalSearch.svelte
packages/@sparrow-common/src/components/global-search/sub-components/RecentItems.svelte
packages/@sparrow-common/src/components/global-search/sub-components/SearchSuggestions.svelte

fix: fixed the functional structure []

---

packages/@sparrow-common/tsconfig.json
packages/@sparrow-teams/src/components/api-list-items/ApiListItem.svelte

fix: removed consoles []

---

packages/@sparrow-common/src/components/SearchBar/SearchBar.svelte

fix: color changes []

---

packages/@sparrow-common/src/images/index.ts

Change image name to fix docker fail

fix: changes image name []

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

feat: shorten the app version []

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte

fix: added navigation in web app []

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Upgraded Sparrow version to 2.17.0

feat: upgrade sparrow version to v2.17.0 []

---

packages/@sparrow-common/src/types/workspace/http-request-base.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

change in ui and make REST to REST API using enum 
from
to

fix: the REST to REST API in UI

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte

APP/Webapp- UI issue in rest api section
[#2553](https://github.com/sparrowapp-dev/sparrow-app/issues/2553)
after

APP/Webapp- UI issue in rest api section #2553

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
packages/@sparrow-common/src/components/global-search/sub-components/NoResults.svelte
packages/@sparrow-common/src/components/global-search/sub-components/RecentItems.svelte
packages/@sparrow-library/src/icons/CheckCircle.svelte

Fixed the reported bugs fir release

fix: fixed the reported bugs []

---

packages/@sparrow-library/src/styles/style.scss

fix: added missing color options []

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/package.json
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Upgraded sparrow version to v2.17.1

feat: upgraded sparrow version to v2.17.1 []

---

apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/Testflow.ViewModel.ts

fix: fixed recent env and flow in edge []

---

packages/@sparrow-library/src/ui/modal/Modal.svelte

https://techdome.atlassian.net/browse/SPRW-61 
Updated Modal Component as per DS.

feat: updated the Modal Component []

---

packages/@sparrow-library/src/ui/badge/Badge.svelte

Please do not leave this blank .
I have updated the badge component[SPRW-41]

Fix: In Ds badge Component.

---

packages/@sparrow-library/src/forms/search/Search.svelte
packages/@sparrow-teams/src/features/workspace-members/layout/WorkspaceMembers.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte

https://techdome.atlassian.net/browse/SPRW-37

input search bar updates

---

packages/@sparrow-common/src/components/SearchBar/SearchBar.svelte
packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-library/src/forms/select/Select.svelte

Added new dropdown header states

feat: added dropdown header states []

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

fix: collection list open issue []

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte

(https://techdome.atlassian.net/browse/SPRW-103)
[Teams & Workspace] UI glitch while creating workspace
now working

[Teams & Workspace] UI glitch while creating workspace

---

apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte

fix: fixed the open collection issue []

---

packages/@sparrow-library/src/ui/toast/Toast.ts

Please do not leave this blank 
I have added a maximum limit for the number of toast messages that can be displayed on the screen.

Fix: DS Toast Message Limit.

---

packages/@sparrow-workspaces/src/components/combo-text/ComboText.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-default-screen/ResponseDefaultScreen.svelte

Keyboard shortcuts:bug fix

---

packages/@sparrow-library/src/ui/navigator/Navigator.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-status/ResponseStatus.svelte

fix: fixed ui issues []

---

packages/@sparrow-library/src/forms/search/Search.svelte
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte

fix: fixed color issues []

---

packages/@sparrow-library/src/ui/navigator/Navigator.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte

fix: shortcut bug and toggle bug 

---

packages/@sparrow-library/src/ui/chip/Chip.svelte
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte

feat: add error focus state chip

---

packages/@sparrow-library/src/forms/checkbox/Checkbox.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte

disable state and no focus on disable state

updates in ds-checkbox

---

packages/@sparrow-library/src/ui/modal/Modal.svelte

fix: fixed the modal ui issue []

---

packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte

https://techdome.atlassian.net/browse/SPRW-39

updates in ds-page-navigation

---

packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

no setting option for other than owner

updates in ds-tabs

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: Upgraded the sparrow version to v2.18.0 []

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte

slider not properly align in graph ql response section

bug in ds-tabs graphQL

---

packages/@sparrow-library/src/ui/button/Button.svelte

updates in button add extra small

---

.github/workflows/sparrow-web-design-system.yml
.github/workflows/sparrow-web-dev.yml
.github/workflows/sparrow-web-prod.yml

build: Updated dockerfile name in web workflow []

---

apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte

fix: global search import []

---

packages/@sparrow-common/src/features/global-search/components/SuggestionTags/SuggestionTags.svelte
packages/@sparrow-common/src/features/global-search/layout/GlobalSearch.svelte
packages/@sparrow-library/src/icons/ArrowSwapRegular.svelte
packages/@sparrow-library/src/icons/FlowChartRegular.svelte
packages/@sparrow-library/src/icons/FolderRegular.svelte
packages/@sparrow-library/src/icons/LayerRegular.svelte
packages/@sparrow-library/src/icons/StackRegular.svelte
packages/@sparrow-library/src/icons/WorkspaceRegular.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-library/src/ui/chip/FilterChip.svelte
packages/@sparrow-library/src/ui/chip/index.ts

https://techdome.atlassian.net/browse/SPRW-111

Filter chips

---

packages/@sparrow-library/src/icons/SaveRegular.svelte
packages/@sparrow-library/src/icons/disk.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/utils/url-input-theme.ts

Sprw 108 ds api component

---

packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-library/src/icons/CaretDownFilled.svelte
packages/@sparrow-library/src/icons/CaretDownRegular.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte

changed select icon , remove "a" from web socket input , added missing disable state in graph ql

changed select icon

---

apps/@sparrow-web/src/components/App.ts

Fixed the take tour functionality issues in webapp which was not coming before for new users.
Fixed the creation of rest api tab and AI window for new users

fix: for new users fixed tour guide ai winodw rest tab creation [#104]

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
packages/@sparrow-library/src/forms/editor/Editor.svelte

Restricted global search to open when response/request body is focused. 
Global search will close on ESC button. 
fix: Messages in global search.

feat: global search feedbacks addresses [SPRW-97]

---

packages/@sparrow-library/src/ui/accordion/Accordion.svelte

I have added label text condition for accordion based on design requirement.

fix: Ds component accordion condition of label.

---

packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte

diasble state in edge in + button teams panel

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte

I have fixed the position of the preview test card.

fix: preview test flow card Icon position.

---

packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/RequestAuth.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/api-key/ApiKey.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/bearer-token/BearerToken.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/form-data/FormData.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/raw/Raw.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/url-encoded/UrlEncoded.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-headers/RequestHeaders.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-parameters/RequestParameters.svelte

fix: disable all the saved response properties

fix: disable all the saved response properties

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-desktop/src/services/collection.service.ts
packages/@sparrow-common/src/enums/mixpanel-events.enum.ts
packages/@sparrow-common/src/types/workspace/collection-base.ts
packages/@sparrow-common/src/types/workspace/http-request-saved-dto.ts
packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte

feat: added left panel options in save response [}

---

packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-headers/RequestHeaders.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-parameters/RequestParameters.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

feat: disable web app saved response

feat: disable web app saved response

---

packages/@sparrow-library/src/forms/editor/Editor.svelte

fix: added cmd option also for the mac in editor []

---

packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/layout/RestExplorerSaved.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte

fix: adjust splitter width to handle 0 apacity in between split

fix: adjust splitter width to handle 0 apacity in between split

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte

feat: upgraded sparrow version to 2.19.0 []

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

Added support of Save API Response in Sparrow Edge for App

feat: added save api response in sparrow edge in app [SPRW-316]

---

packages/@sparrow-library/src/ui/options/Options.svelte

Fixed the LHS popup alignment issue, we can later enhance it more by providing the dynamic width and height to the popup according to the popup content in the "Options" component.

LHS popup alignment fix [#102]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte

This PR fixes the issue of root level input arguments not getting recognized in the query editor.

fix: root level input fields in query editor

---

packages/@sparrow-common/src/components/header/sub-component/UserProfileModal.svelte
packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte
packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte

fixed avatar in delete workspaces , fixed z index of tooltip of profile icon in topbar, fixed wrong minimize icon when opened bug

Sprw 325 general UI issues

---

packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte

AI-chat-bot

---

apps/@sparrow-desktop/src/adapter/request-tab.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/adapter/request-tab.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/rest-explorer/utils/decode-request.ts

feat: implement testflows for web and desktop

feat: implement testflows for web and desktop

---

packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

fix: replaced options with dropdown component []

---

packages/@sparrow-workspaces/src/utils/url-input-theme.ts

I have resolved the issue of CodeMirrorInput Hover state.

fix: resolved text moving issue on hover in CodeMirrorInput.

---

packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

updates in leftWorkspace panel

---

apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-web/src/repositories/collection.repository.ts

fix: saving http requests deletes saved request

fix: saving http requests deletes saved request

---

packages/@sparrow-library/src/forms/Input/Input.svelte

feat: implement input primary

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte

updates in stroke-text-field

---

packages/@sparrow-workspaces/src/features/workspace-tour-guide/layout/WorkspaceTourGuide.svelte

I have resolved the issue with dismiss button

Fix: issue with the dismiss button.

---

packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte

I have updated the existing dropdown design according to the new design system (DS) specifications.

Feat: Updated dropdown with new DS design.

---

packages/@sparrow-library/src/ui/alert/Alert.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-error-screen/ResponseErrorScreen.svelte

updates in alert component

---

packages/@sparrow-library/src/ui/button/Button.svelte

updates in button

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-library/src/icons/SaveRegular.svelte
packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte

changed bg and fixed icon

---

apps/@sparrow-desktop/src/adapter/collection-tab.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/adapter/collection-tab.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

feat: implement set auth

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts

I have corrected the redirecting issue in the dropdown.

fix: resolved issue with redirecting

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-error-screen/ResponseErrorScreen.svelte

updates in testflow alert component

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte

I have resolved all the small UI issues in the GraphQL DS support.

fix: resolved ui issues in Ds support Graphql

---

packages/@sparrow-workspaces/src/features/welcome-popup/layout/WelcomePopup.svelte

I have updated the button name according to the figma.

fix: updated the button name on the Welcome card

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts

fix: auth navigation unsaved changes and collection level auth refresh

fix: auth navigation unsaved changes and collection level auth rerfresh

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: upgraded the sparrow version to v2.20.0 []

---

.github/ISSUE_TEMPLATE/--bug-report.yaml

Updated the --bug-report.yaml to include other fields

---

.github/ISSUE_TEMPLATE/--feature-request.yaml

Updated the --feature-request.yaml

---

apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
packages/@sparrow-library/src/ui/image-modal/ImageModal.svelte
packages/@sparrow-library/src/ui/modal/Modal.svelte

Sprw 398 close popups on pressing escape key

---

packages/@sparrow-library/src/forms/editor/theme.ts

I have changed the complete UI of the Search feature in the code editor and applied DS component styles to it.

feat: Improve search in code editor

---

.github/workflows/github-to-jira.yml

Updated the github-to-jira.yml file with few changes as the workflow was breaking.

Updated the github-to-jira.yml file with few changes

---

packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte

updates in  left workspace panel

---

packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte

Implentation ctrl z ctrl y

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/response-error-screen/ResponseErrorScreen.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

try button is not working in global enviroment variable case

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/services/collection.service.ts
apps/@sparrow-desktop/src/services/collection.ts
apps/@sparrow-desktop/src/services/rest-api.service.ts
apps/@sparrow-web/src/containers/api/api.common.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/services/collection.service.ts
apps/@sparrow-web/src/services/collection.ts
apps/@sparrow-web/src/services/rest-api.service.ts
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte

fix: import collection viewModel flow and issues.

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte

fix: pagination issue while search in workspace

---

packages/@sparrow-library/src/ui/toggle/Toggle.svelte
packages/@sparrow-workspaces/src/components/missed-environment/MissedEnvironment.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/none/None.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/none/None.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-headers/ResponseHeaders.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
packages/@sparrow-workspaces/src/hoc/WithSelectV3.svelte

fixed ui bugs in rest and also fixed paddings in socket and socketio
Fixes #2834

Rest ui issues

---

packages/@sparrow-library/src/ui/modal/Modal.svelte

fix: modal cross icon [412]

---

apps/@sparrow-desktop/src/adapter/request-saved-tab.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-web/src/adapter/request-saved-tab.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
apps/@sparrow-web/src/repositories/collection.repository.ts
packages/@sparrow-common/src/types/workspace/http-request-saved-base.ts
packages/@sparrow-common/src/types/workspace/http-request-saved-dto.ts
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/layout/RestExplorerSaved.svelte

This PR provide a functionality to save the response body type. 
It also fix issue of saved response not coming with proper type of body. 

feat: added feature to save response body type [SPRW-366]

---

packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte

Login to the Sparrow app and go to the left panel in the workspace
Open collections and environment tab
Collapse the collection where data exists
Select any environment
Actual Result: Selection of environemnt is expanding the collection
#2341 
Selection of environemnt is expanding the collection

Update in left workspace 

---

apps/@sparrow-web/src/adapter/graphql-tab.ts
apps/@sparrow-web/src/services/collection.service.ts

fix: graphql save mutation issue for web app

fix: graphql save mutation issue for web app

---

packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte

I have Implemented Ds Support Teams - Invite Members workspace
Fixes #2856 

Teams - Invite Member Workspace

---

packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte

updates in left panel

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts

Made collection and environment explorer page temporary for first time open

fix: made collection and environmemnt page temporary []

---

apps/@sparrow-desktop/src/adapter/request-tab.ts
apps/@sparrow-web/src/adapter/request-tab.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-body/ResponseBody.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte

fix: graphql missed imports for web

---

apps/@sparrow-web/src/containers/api/api.common.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-common/src/utils/status-code.ts

fix: handle catch block for handling api response

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Upgraded the sparrow version to 2.21.0

feat: upgraded the sparrow version to 2.21.0 []

---

apps/@sparrow-desktop/src/components/app.ViewModel.ts
apps/@sparrow-desktop/src/pages/auth-page/Auth.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/components/App.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/Teams/Teams.svelte
packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-common/src/features/create-team/constants/description.ts
packages/@sparrow-common/src/features/create-team/constants/name.ts
packages/@sparrow-teams/src/features/leave-team/layout/LeaveTeam.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte
packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte

In this PR i have updated the team terminology with hub for end user in UI at all modules.
SPRW-557

feat: updated team to hub for user [SPRW-557]

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
packages/@sparrow-workspaces/src/utils/tabular-input-theme.ts

With the introduction of the Sparrow Design System there needs to be rules defined for  min width max width, position behaviour etc as per the documentation which would be provided by the design team.
- [*] **The pull request only addresses one issue or adds one feature.**
- [*] **I have linked a PR type label to the pull request.**
- [*] **The pull request does not introduce any breaking changes**
- [*] **I have read the [contribution guidelines](../../docs/CONTRIBUTING.md).**

feat:  Key value pairs

---

apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-teams/src/features/team-members/components/member/Member.svelte

Astitva/hub UI changes

---

apps/@sparrow-desktop/src/adapter/folder-tab.ts
apps/@sparrow-desktop/src/adapter/index.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
apps/@sparrow-desktop/src/repositories/tab.repository.ts
apps/@sparrow-web/src/adapter/folder-tab.ts
apps/@sparrow-web/src/adapter/index.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
apps/@sparrow-web/src/repositories/tab.repository.ts
packages/@sparrow-common/src/types/workspace/folder-tab.ts
packages/@sparrow-common/src/utils/init-folder-tab.ts
packages/@sparrow-common/src/utils/init-request-tab.ts
packages/@sparrow-common/src/utils/init-workspace-tab.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte

feat: add folder save button to web and desktop app

feat: add folder save button to web and desktop app

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte

I have updated the GraphQL screen with the correct padding and gap sizes as mentioned in the Figma design.
Fixes # available in Jira [SPRW-550]
[SPRW-550]: https://techdome.atlassian.net/browse/SPRW-550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Graphql padding issue.

---

.github/workflows/sparrow-web-dev.yml
.github/workflows/sparrow-web-prod.yml

build: Added new ENV in dev []

---

packages/@sparrow-workspaces/src/components/test-flow-bottom-panel-navbar/TestFlowBottomPanelNavbar.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body/ResponseBody.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-status/ResponseStatus.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

fix bugs in the bottom panel in test flow.

fix: test-flow bottom panel bugs 

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte

fix: test-flow bottom panel bugs

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/services/ai-assistant.ws.service.ts

Multiple reconnection attempts was happening on switching to different accounts. Solved this issue to main the consistency in manage the connection events.

fix: fixed multiple reconnection attempts for websocket

---

packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

The object for state was missing in the Request Data for the drag-and-drop functionality. I have updated it correctly. and solved UI tool tip alignment issue.
Fixes # jira not available

fix: Test flow drag and drop body issue.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/services/collection.service.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
apps/@sparrow-web/src/services/collection.service.ts

In this  PR i have updated the url route of Collection and request level APIs with sparrow hub url. 

feat: added huburl route for collection level apis []

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

fix  the selected response format is saved and restored when saving API via top panel
https://github.com/user-attachments/assets/cfdf3d94-edb6-4a26-8f82-c6901ebca7ad

fix: save response format correctly from top panel

---

apps/@sparrow-desktop/src/containers/api/api.common.ts

Reverts sparrowapp-dev/sparrow-app#2935

Revert "feat: added x-app-version header for testing []"

---

packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte

feat: teams-and-workspaces-invite-flow

feat: teams-and-workspaces-invite-flow

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

Fix the base url while deleting response.

fix the delete response for web and desktop.

---

packages/@sparrow-library/src/icons/SettingsRegular.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte

In this I have fixed the text-size in delete pop-up and icons size in workspace.

fix: text-size in delete pop-up and icons size in workspace.

---

packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte

Fix the sidebar toggle when collection is the active tab.

fix:sidebar-toggle

---

apps/@sparrow-web/index.html
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Bug fixes:
1. Adjusting the quick help panel position on chatbot open state
2. Renamed the ai model name
3. Fixed the dropdown body height
4. Removing the like/dislike options for the empty messages

fix: ui fixes for chatbot panel and model rename

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-desktop/src/services/collection.service.ts
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-library/src/ui/tags/Tags.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

feat: added active sync in app [SPRW-561]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte

Updated the sync api logic for folder in active sync and added rename folder option. 

fix: updated the folder sync logic in active sync[]

---

apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
apps/@sparrow-web/src/services/collection.service.ts
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte

feat: added active sync in web app [SPRW-561]

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte

I have resolved the issue regarding the hover issue on arrow icon.
Fixes # jira SPRW-428
not appliable it looks same.

fix: Test flow arrow hover issue.

---

packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte

fix: resolve env UI breaking issue

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-web/src/containers/api/api.common.ts

Added new header x-app-version for all API's in web and app. 

feat: added x-app-version header in Headers of all APIs []

---

apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
packages/@sparrow-common/src/features/sidebar/components/SidebarItem.svelte
packages/@sparrow-common/src/features/sidebar/layout/Sidebar.svelte

solved ui issues

---

packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte

Remove onSaveWorkSpace from if condition as this check is unnecessary.

fix: remove onSaveWorkSapce check

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-desktop/src/repositories/team.repository.ts
apps/@sparrow-desktop/src/services/team.service.ts
packages/@sparrow-library/src/icons/MoreVerticalRegular.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-teams/src/components/table/Table.svelte
packages/@sparrow-teams/src/compopnents/menu-view/MenuView.svelte
packages/@sparrow-teams/src/constants/TeamTabs.constants.ts
packages/@sparrow-teams/src/features/index.ts
packages/@sparrow-teams/src/features/invited-users/components/InviteRow.svelte
packages/@sparrow-teams/src/features/invited-users/index.ts
packages/@sparrow-teams/src/features/invited-users/layout/InvitesView.svelte
packages/@sparrow-teams/src/features/invited-users/layout/index.ts
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte

implemented invite flow functionality where user can invite other user, the receiver can accept the invitation from the app or from the email , the sender can also view the list of invitation sent 
Fixes #2959
after withdrawing all invites the navigator has its old state

Invite flow non registered

---

packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte

fix: fixed sync for deployed url []

---

apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/repositories/team.repository.ts
apps/@sparrow-web/src/services/team.service.ts
packages/@sparrow-teams/src/features/invited-users/components/InviteRow.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

implemented invite flow in web 
Fixes  ##2959
few navigator issues are there

feat:Invite flow non registered

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/services/collection.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/services/collection.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
packages/@sparrow-workspaces/src/stores/active-sync.ts
packages/@sparrow-workspaces/src/stores/index.ts

fix: fixed active sync UI issues []

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte

I have resolved of overflowing of request time in run history. 
Fixes # SPRW-730

fix: Test flow overflowing issue with long request time.

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

remove unused chars at testflow

fix: unused-char-for-testflow

---

packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

fix: restrict active sync collection in save popup []

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

Restricted sync functionality for viewer and allowed for editor. 
Fixed request count issue in folder. 

fix: restricted active sync for viewer and folder level count []

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Sparrow version bump tp 2.22.0

feat: sparrow version upgrade v 2.22.0 []

---

packages/@sparrow-common/src/components/header/Header.svelte

Fix the workspace dropdown according to design.

fix workspace dropdown.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte

fix:text-size and toast in delete response pop-up.

fix:text-size and toast in delete response pop-up.

---

apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/collection.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/collection.model.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/repositories/collection.repository.ts
packages/@sparrow-common/src/types/workspace/collection-base.ts
packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

Solved bugs of active sync:
Fixed zindex issue. 
Added last synced field. 

fix: solved active sync bugs [SPRW-731]

---

packages/@sparrow-library/src/forms/editor/theme.ts

Fix the background of active line in editor.

Fix the background of active line in editor.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts

The red dot appearance/disappearance was delayed due to a 1000ms debounce; removed the delay to ensure seamless updates.
https://github.com/user-attachments/assets/b27e4a2e-5111-4575-859b-6025fc47947b

fix: red dot appearance and disappearance delay

---

packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-library/src/icons/MathFormulaRegular.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/index.ts
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/index.ts
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/index.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

added dynamic expression to codemirror

fix: added dynamic expression to codemirror

---

packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/api-key/ApiKey.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/sub-auth/basic-auth/BasicAuth.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/api-key/ApiKey.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte

soled a url width bug
Fixes #2989 
not applicable

fix: codemirror field width

---

packages/@sparrow-library/src/ui/toast/Toast.svelte
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

Fix the appearance of toast message above the modal.

fix the appearance of toast component.

---

packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte

I have updated Error message font according to the Figma.
Fixes # SRPW-787

fix: Error message size issue.

---

packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

[Add your description here.](fix: testflow tab selections for body and auth)

fix: testflow tab selections for body and auth

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte

Added Replace collection popup 

fix: added replace collection popup [SPRW-731]

---

apps/@sparrow-desktop/src/components/app.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte

fix issue where in user gets logged into unknown account when opening desktop application via deeplink with sparrow edge on browser
Fixes #[715](https://techdome.atlassian.net/browse/SPRW-715)
not applicable, functional bug.

fix: deeplink bugs  and typo

---

packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

Added condition so that last synced condition will be visible for active sync collection only. 

fix: fixed the last synced condition [SPRW-621]

---

.github/workflows/sparrow-app-development.yml

fix: update S3 upload command to correctly reference dmg directory

---

apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte

Fix the redirection of feedback url on click of report issue button.

fix:redirection of report issue button. [SPRW-696]

---

packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte

fix the opening of collection, folder and request tab on click of expand button. [https://techdome.atlassian.net/browse/SPRW-764]

fix the opening of collection, folder and request tab on click of expand button.

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

App version upgrade to 2.22.1
Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to

feat: add 2.22.1 patch release version

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-common/src/utils/testFlow.helper.ts
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

Patch 2 22 1

---

.github/workflows/sparrow-bot.yml

fix: update GitHub token secret for Sparrow Bot workflows

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte

fix the workspacelist  header overlapping in mac .

fix the workspacelist  header overlapping in mac.

---

packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte

removed "new request" in tab bar
Fixes #3022

fix: removed "new request" in tab bar SPRW-767

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-web/src/components/App.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
packages/@sparrow-common/src/features/index.ts
packages/@sparrow-common/src/features/public-workspace/index.ts
packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
packages/@sparrow-common/src/features/public-workspace/layout/index.ts
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte

Added modal for permission of public workspace 

feat: added workspace public modal [SPRW-853]

---

packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte

Update the UI of workspace.

---

packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have updated the dynamic expression model.

feat: Dynamic expression model.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-web/src/components/App.ts
packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte

fix: fixed ui changes of public workspace. 

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/components/test-flow-bottom-panel-navbar/TestFlowBottomPanelNavbar.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte

feat: add handler to run preview

---

packages/@sparrow-library/src/ui/tags/Tags.svelte
packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

Fixed public private filter and ui changes 

fix: fixed UI changes in workspace []

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte

I have updated the few issue in the dynamic expression.

Fix: dynamic expression model issues.

---

packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/TeamsProfile.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
packages/@sparrow-teams/src/features/team-settings/layout/TeamSettings.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-updates/WorkspaceUpdates.svelte

fix: solved public workspace UI bugs [SPRW-895]

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte

feat: fix dynamic expression drag and drop

feat: fix dynamic expression drag and drop

---

packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte

fix: added word count in description [SPRW-895]

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

By adding a specific prompt to 4xx error debug buttons and modifying the AI instructions, we are segregating the changes suggest for 4xx errors suggestions and normal improvements suggestions from AI. It will trigger 4xx error instructions but in normal case it should give normal enhancement, and improvement suggestions.
This PR also contains code refactoring for copilot feature.
AI suggested to add creator_id
AI suggested to simplify the accept header

feat: enabling suggestions of normal user queries + code refactoring

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte

Revert "feat: fix dynamic expression drag and drop"

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Reverts sparrowapp-dev/sparrow-app#3062

Revert "feat: enabling suggestions of normal user queries + code refactoring"

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-desktop/src/main.ts
apps/@sparrow-web/src/containers/api/api.common.ts
apps/@sparrow-web/src/main.ts

Fix the usable sentry logs.

---

apps/@sparrow-web/package.json

Add pakage.json commited posthog.js 
Fixes [SPRW-822](https://techdome.atlassian.net/browse/SPRW-822)
[SPRW-822]: https://techdome.atlassian.net/browse/SPRW-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

added:package-web-posthog-added [SPRW-822]

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: upgrade version bump [#1]

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Reverts sparrowapp-dev/sparrow-app#3094

Revert "feat: upgrade version bump [#1]"

---

yarn.lock

feat: upgrade posthog [#1]

---

packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte

Fixed type in workspace, made you --> your. 

fix: fixed type in workspace []

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
packages/@sparrow-workspaces/src/components/tabular-input/sub-component/BulkEditEditor.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte

Fixed the typo at some places and disabled the deepseek option.

fix: fixed the typo and disabled the deepseek option [SPRW-943, SPRW-944]

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json
packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte

fix: add patch v2-23-1

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

SPRW-879 implement in between testflow block storage

---

packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I’ve updated the logic to ensure that only the single test flow block is selected, rather than all connected blocks.
Fixes # jira
https://github.com/user-attachments/assets/f014453c-0aee-4425-a093-58d5a135c123

feat: Test flow Delete single block SPRW-877.

---

packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have updated the dynamic expression for deleting block connections accordingly and added a pop-up model if the API is used in another API.
Fixes # jira

feat: Testflow connecting deleting Block SPRW-878

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
packages/@sparrow-library/src/ui/modal/Modal.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have added a question mark icon that redirects users to Sparrow Docs when clicked.
Fixes # not available.

fix: Dynamic Expression Question mark Icon Redirect Handling SPRW-896.

---

packages/@sparrow-library/src/ui/alert/Alert.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte

Added an alert when a user includes an environment variable in the URL without declaring it we will show the alert pop up.
Fixes # jira SPRW-761

feat: Testflow Enhancement for environment usage.

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte

If user click "Ctrl + Enter" from keyboard, then Graph outline is not turning red
Fixes #3086

fix:added red border to graph ql and rest 

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte

Added a spinner to prevent default first page flash during initial API call delay

fix: add spinner to handle loading delay on initial API call

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have fixed the dynamic expression cursor issue related to adding requests and corrected the regex expression for deleting an expression, ensuring proper validation of dynamic expressions and preventing unintended deletions.

fix: testflow deleting correction  SPRW-896

---

packages/@sparrow-common/src/types/workspace/collection-base.ts
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte

Filtered collection with collection type

feat: added mock collection type filter [SPRW-957]

---

apps/@sparrow-desktop/src/main.ts
apps/@sparrow-web/src/main.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

fix: commented the regular type fluent icon import []

---

apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
packages/@sparrow-common/src/features/create-team/constants/description.ts
packages/@sparrow-common/src/features/create-team/constants/icon.ts
packages/@sparrow-common/src/features/create-team/constants/name.ts
packages/@sparrow-library/src/forms/Input/Input.svelte
packages/@sparrow-library/src/forms/label-field/LabelField.svelte
packages/@sparrow-library/src/ui/modal/Modal.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-links/TeamLinks.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte

Fix the ui bugs of public workspaces [SPRW-902].
- [ x] **I have read the [contribution guidelines](../../docs/CONTRIBUTING.md).**
[SPRW-902]: https://techdome.atlassian.net/browse/SPRW-902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the ui bugs of public workspaces [SPRW-902].

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte
packages/@sparrow-library/src/ui/tags/Tags.svelte
packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte

Fix the UI bugs of public workspace [SPRW-911].
[SPRW-911]: https://techdome.atlassian.net/browse/SPRW-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the UI bugs of public workspace [SPRW-911]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-common/src/dto/collection.ts
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

feat: added mock collection function []

---

apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

feat: added mock collection create in web []

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
packages/@sparrow-common/src/types/workspace/http-request-tab.ts
packages/@sparrow-common/src/utils/init-request-tab.ts
packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte
packages/@sparrow-workspaces/src/features/chat-bot/layout/ChatBot.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Added deepseek model support and change in the model select dropdown UI

feat: deepseek model support and disabling other model for now [SPRW-667]

---

packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

Fix ui and functional bugs of workspaces [SPRW-981].
[SPRW-981]: https://techdome.atlassian.net/browse/SPRW-981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix ui and functional bugs of workspaces [SPRW-981].

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/empty-collection/EmptyCollection.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

implement delete mock collection.

feat: implement delete mock collection [SPRW-959]

---

packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte

show only REST API in mock folder delete model

fix: mock collection folder and rename [SPRW-958]

---

packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte

Fixed app not loading when document not coming. 

fix: fixed app crash on register []

---

packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/edge/Edge.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

SPRW-983 feat: implement testflow blocks rewiring

SPRW-983 feat: implement testflow blocks rewiring

---

packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have updated the model along with the changes in nodes alignment. 

Fix: dynamic expression condition model correction. 

---

packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte

I have fixed the scroll without header.
Fixes #jira

fix: Left panel test flow scroll issue SPRW-969.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte

add folder explorer for mock collection

Feat: add folder explorer for mock collection

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

fix: testflow UI alignment bugs

fix: testflow UI alignment bugs

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

I have updated the UI issues in the test flow tour guide according to the figma . 
Fixes #jira

Fix: test flow tour guide UI issue SPRW-678

---

packages/@sparrow-workspaces/src/components/delete-node/DeleteNode.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-block/RequestBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

feat: implement dynamic expression dependency check

feat: implement dynamic expression dependency check

---

apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/collection.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-desktop/src/services/collection.service.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/collection.model.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/repositories/collection.repository.ts
apps/@sparrow-web/src/services/collection.service.ts
packages/@sparrow-common/src/types/workspace/collection-base.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

Added mock request creation flow in folder level 
Added mock server running status property. 

feat: added mock request creation in folder and mock running status [SPRW-1008]

---

packages/@sparrow-library/src/ui/alert/Alert.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte

I have updated it to support full width based on the parent component.
Fixes #jira

Fix: test flow environment miss alert size issue SPRW-761  

---

packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-description/UpdateTeamDescription.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/edge/Edge.svelte

fix: teams UI Design

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/mock-request/MockRequest.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/http-status-codes.ts
packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/index.ts
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte

mock rest api, tab type and status code

feat: mock rest api, tab type and status code [SPRW-1009]

---

packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

Add search functionality in select component.

Fix: make select component searchable

---

packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/utils/functionOptionsData.ts

I have added two JSON options to select by user. 
Fixes #jira

Fix: Dynamic Expression Functions Options of JSON  SPRW-928

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

Mock REST API toast notification.

fix: Mock REST API toast notification

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

fix: fixed mock rest api not creating from collection explorer page [SPRW-1056]

---

packages/@sparrow-common/src/types/workspace/tab.ts
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
packages/@sparrow-workspaces/src/utils/index.ts
packages/@sparrow-workspaces/src/utils/mock-url-input-theme.ts

Mock rest api url input, divide url input in two parts.

Fix: mock restapi url space

---

packages/@sparrow-workspaces/src/features/collection-list/components/mock-request/MockRequest.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/utils/http-status-codes.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

fix: fixed mock server bugs [SPRW-1056]

---

apps/@sparrow-desktop/src-tauri/Cargo.toml

Added windows only flag in dependency of cargo.toml

Group policy research

---

packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte

Fix font style for code in chatbot.

fix: chatbot code font style [SPRW-942]

---

packages/@sparrow-common/src/features/published-workspace/layout/PublishedWorkspace.svelte
packages/@sparrow-library/src/ui/modal/Modal.svelte

Fix overflow hidden property for the modal component.

Fix overflow hidden property for the modal component [SPRW-1065].

---

packages/@sparrow-common/src/components/header/Header.svelte

Add space between profile icon and right boundary in Mac.

fix: profile icon spacing

---

packages/@sparrow-library/src/forms/editor/MergeViewNavigation.svelte
packages/@sparrow-library/src/forms/editor/mergeViewUtil.ts

fix: file name fix

---

packages/@sparrow-common/src/components/header/Header.svelte

Reverts sparrowapp-dev/sparrow-app#3176

Revert "fix: profile icon spacing"

---

apps/@sparrow-web/src/components/App.ts

This PR adds redirect url for hubs and workspace, to redirecyt from admin app

fix: add-redirects

---

packages/@sparrow-common/src/components/header/Header.svelte

Reverts sparrowapp-dev/sparrow-app#3167

Revert "fix: add space in profile icon and right boundary [SPRW-986]"

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/dynamic-content/DynamicContent.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/expression-editor/ExpressionEditor.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte
packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte

feat: enable editor copy text

---

packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

fix: cropped api response

---

packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

fix: fixed condition comparison issue, updated dropdown for desktop

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

fix workspaces count and members tab.

fix workspaces count and members tab.

---

apps/@sparrow-desktop/src/adapter/mock-history-tab.ts
apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/collection.model.ts
apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
apps/@sparrow-web/src/adapter/mock-history-tab.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/collection.model.ts
apps/@sparrow-web/src/models/tab.model.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
packages/@sparrow-common/src/factory/init-tab.ts
packages/@sparrow-common/src/types/workspace/collection-base.ts
packages/@sparrow-common/src/types/workspace/collection-dto.ts
packages/@sparrow-common/src/types/workspace/http-request-base.ts
packages/@sparrow-common/src/types/workspace/http-request-mock-base.ts
packages/@sparrow-common/src/types/workspace/mock-history-tab.ts
packages/@sparrow-common/src/types/workspace/tab.ts
packages/@sparrow-common/src/utils/init-mock-history-tab.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/index.ts
packages/@sparrow-workspaces/src/features/mock-history-explorer/index.ts
packages/@sparrow-workspaces/src/features/mock-history-explorer/layout/MockHistoryExplorer.svelte

In this PR i have added Mock History page and updated tab and collection model for history data. 

feat: added history model and explorer page [SPRW-1030]

---

packages/@sparrow-teams/src/features/invited-users/layout/InvitesView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/edge/Edge.svelte

fix: testflow operation UI

---

apps/@sparrow-desktop/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.svelte
apps/@sparrow-desktop/src/repositories/workspace.repository.ts
apps/@sparrow-desktop/src/services/workspace.service.ts
packages/@sparrow-marketplace/src/features/marketplace-explorer/layout/MarketplaceExplorer.svelte

Added fetch public workspace flow. 
Added paginated api for this. 

feat: added paginated fetch public workspace flow [SPRW-1033]

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: app version upgrade

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

Added history details in collection page and added it's navigation. 

feat: added view history and navigation [SPRW-1030]

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
packages/@sparrow-common/src/features/global-search/components/RecentItems/sub-components/NoResults.svelte

fix: testflow renders from global search [SPRW-1141]
[SPRW-1141]: https://techdome.atlassian.net/browse/SPRW-1141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: testflow renders from global search [SPRW-1141]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts

fix: removed unused libraries and imports

fix: removed unused libraries and imports []

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.ViewModel.ts

Add import for toast notification.

fix: add notifications import [SPRW-1082]

---

apps/@sparrow-desktop/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-web/src/pages/marketplace-page/sub-pages/MarketplaceExplorerPage/MarketplaceExplorerPage.svelte
packages/@sparrow-common/src/components/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-marketplace/src/features/marketplace-explorer/layout/MarketplaceExplorer.svelte

 Fix the marketplace bugs .

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts

fix: global search path for testflow and environment [SPRW-931]
[SPRW-931]: https://techdome.atlassian.net/browse/SPRW-931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: global search path for testflow and environment [SPRW-931]

---

packages/@sparrow-common/src/components/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-marketplace/src/features/marketplace-explorer/layout/MarketplaceExplorer.svelte

Fix the bugs in the workspace grid card.

Fix the bugs in the workspace grid card.

---

packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/HistoryTable.svelte

Make history table row clickable.

fix: history table row expand behavior on click [SPRW-1094]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte

Add the collection page for the shared workspaces.

Add the collection page for the shared workspaces.

---

packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Enabled "Help me Debug" button for 5xx status codes as well, to help users troubleshoot client side errors as well.

feat: enabled AI debugging for 5xx status codes [SPRW-1020]

---

apps/@sparrow-desktop/src/adapter/hub-tab.ts
apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/HubExplorerPage/HubExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-desktop/src/services/team.service.ts
apps/@sparrow-web/src/adapter/hub-tab.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/tab.model.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/HubExplorerPage/HubExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-web/src/services/team.service.ts
packages/@sparrow-common/src/factory/init-tab.ts
packages/@sparrow-common/src/types/workspace/hub-tab.ts
packages/@sparrow-common/src/types/workspace/tab.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-common/src/utils/init-hub-tab.ts
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte

Added hub tab details page. 
Update tab model. 
Added adapter and models for hub in tab. 
added hub explorer page

feat: added hub tab details page [SPRW-1034]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

fix viewflow flow change [SPRW-1037]
[SPRW-1037]: https://techdome.atlassian.net/browse/SPRW-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix viewflow flow change [SPRW-1037]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte

Fix the viewer flow for graphql [SPRW-1038]
[SPRW-1038]: https://techdome.atlassian.net/browse/SPRW-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix the viewer flow for graphql [SPRW-1038]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/HubExplorerPage/HubExplorerPage.svelte
packages/@sparrow-workspaces/src/features/hub-explorer/index.ts
packages/@sparrow-workspaces/src/features/hub-explorer/layout/HubExplorer.svelte
packages/@sparrow-workspaces/src/features/hub-explorer/layout/index.ts
packages/@sparrow-workspaces/src/features/index.ts

Integrated hub page with details. 

feat: integrated hub page with details [SPRW-1036]

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/HubExplorerPage/HubExplorerPage.svelte
packages/@sparrow-workspaces/src/features/hub-explorer/layout/HubExplorer.svelte

Add hub page [SPRW-1039]
[SPRW-1039]: https://techdome.atlassian.net/browse/SPRW-1039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add hub page [SPRW-1039]

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/recent-workspace.repository.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/repositories/recent-workspace.repository.ts
packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-library/src/forms/select/menu-items/MenuItemsv2.svelte

Completed the switch dropdown functionality. 
Changed it for both public and private workspaces. 

feat: completed the Switch dropdown [SPRW-1087]

---

packages/@sparrow-marketplace/src/features/recent-public-workspaces/layout/RecentPublicWorkspace.svelte

Fix: scrolling on recent public workspaces.

fix: scrolling on recent public workspaces.

---

packages/@sparrow-common/src/features/public-workspace/layout/PublicWorkspace.svelte

Fix the public workspace modal text and alignment of checkbox.

Fix the public workspace modal text and alignment of checkbox.

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/repositories/workspace.repository.ts
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/repositories/workspace.repository.ts
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/mock-history-explorer/components/history-table/sub-component/history-table-expanded/HistoryTableExpanded.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-doc/RequestDoc.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

fixed the mock collection in LHS search and restricted public workspace deletion on refresh workspace [SPRW-1154]
[SPRW-1154]: https://techdome.atlassian.net/browse/SPRW-1154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: fixed the mock collection in LHS search and restricted workspace [SPRW-1154]

---

apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/tab.model.ts
packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte

feat: implement loader for environment and testflow creation [SPRW-751]
[SPRW-751]: https://techdome.atlassian.net/browse/SPRW-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: implement loader for environment and testflow creation [SPRW-751]

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

Fix the empty workspace page on applying different filters.

Fix the empty workspace page

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

Display raw URL directly as query parameters already added in URL.

fix: curl import bug [SPRW-1146]

---

.github/workflows/sparrow-plans.yml
apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte

feat: add env to plans pipeline

---

.github/workflows/sparrow-plans.yml

change s3 bucket

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte

Disabled  the marketplace in sparrow edge for web app and desktop app

fix: disabled the marketplace in sparrow edge []

---

apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/plan.model.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/plan.repository.ts
apps/@sparrow-desktop/src/services/plan.service.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/plan.model.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/repositories/plan.repository.ts
apps/@sparrow-web/src/services/plan.service.ts

Sprw 1206 community plan as a user i should not be able to make selective runs in test flows blocks

Sprw 1206 community plan as a user i should not be able to make selective runs in test flows blocks

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Upgraded sparrow version to 2.25.0

feat: upgraded sparrow version to v2.25.0 []

---

packages/@sparrow-common/src/utils/init-ai-request-tab.ts
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-config-selection/AiConfigurations.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/ai-chat-interface/AIChatInterface.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/prompt-input/PromptInput.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/constants/AiModelConfigurations.ts
packages/@sparrow-workspaces/src/features/chat-bot/components/prompt-input/PromptInput.svelte

fix: AI request fixes [SPRW-1216]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
apps/@sparrow-desktop/src/services/collection.service.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
apps/@sparrow-web/src/services/collection.service.ts
packages/@sparrow-common/package.json
packages/@sparrow-common/src/enums/item-type.enum.ts
packages/@sparrow-common/src/types/workspace/http-response-mock-dto.ts
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/no-mock-response-details-section/NoMockResponseDetailsSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

Add mock response integration.

Add mock response integration.

---

apps/@sparrow-desktop/src/pages/help-page/HelpPage.svelte
packages/@sparrow-library/src/icons/FilterRegular.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte
packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
packages/@sparrow-support/src/features/roadmap/layout/Roadmap.svelte

Fix: update style of updates tab

fix: update style of updates tab [SPRW-1027]

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

I have updated the message names for 'User Invite Limit Exceeded' in the user plan.
Fixes #jira

Fix: Sparrow Plan bugs related to message name and invalid name SPRW-1225.

---

packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

In this pr I have render the list of mock responses in the response section.

Render the data in the list [SPRW-1150].

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-web/src/containers/api/api.common.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte

This PR fixes the following problems,
Fixes #3081 
The same-named non-argument field gets auto-selected when the user assigns a value to the argument field in the query editor.
Fixes #2453 
Clicking on the entity names changes the query editor. 
Fixes #3088  
GraqhQL schema loader
https://github.com/user-attachments/assets/965edff2-0cc2-4df3-a466-6afb5eac3821
https://github.com/user-attachments/assets/ab21413a-58a9-483d-a9ef-c060442e33ee
https://github.com/user-attachments/assets/bd94362d-667e-4c1a-a9b7-2e60ca2859f3
No known issues were introduced by fixing this.

fix: multiple graphql issues

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
packages/@sparrow-common/src/types/workspace/http-request-mock-tab.ts

Added responsebody navigation, formatter  etc property in state in mock response. 

feat: added state property in mock response [SPRW-1230]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-body/ResponseBody.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

updated functions to update local tab data of mock response for body, status code and body navigation

feat: updated functions to update local tab data of mock response [SPRW-1230]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts

added rename support for mock response, now rename changes will reflect on the screen in tab

feat: added rename support for mock response [SPRW-1149]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

In this pr ,I have added the functionality of deleting the particular mock response.

Add the functionality of deleting the mock responses [SPRW-1150].

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-headers/ResponseHeaders.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

Add the function to update the headers in mock response 

Add the function to update the headers in mock response [SPRW-1233]

---

.vscode/settings.json
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-desktop/src/services/collection.service.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/repositories/collection.repository.ts
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte

Add the functionality of active and inactive state of mock response

Add the functionality of active and inactive state of mock response [SPRW-1231].

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-auth/RequestAuthTestFlow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-body/RequestBodyTestFlow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-header/RequestHeaderTestFlow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-parameter/RequestParameterTestFlow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte

feat: add environment from testflow

feat: add environment from testflow

---

packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte

Fixed the mock response active state issue 

fix: fixed toggle issue for mock response [SPRW-1149]

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
packages/@sparrow-common/src/components/plan-upgrade-modal/PlanUpgradeModal.svelte
packages/@sparrow-common/src/utils/planUpgradeContent.ts
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/layout/WorkspaceExplorer.svelte

I have added for modal for remaining places in the application and added contact sales.
Fixes #jira

feat: added sparrow plans modal SPRW-1283.

---

.github/workflows/sparrow-app-development.yml

- [*] **The pull request only addresses one issue or adds one feature.**

feat: add needs in workflow & rm unwanted env

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts

add status code for changes comparison

fix: add status code for changes comparison [SPRW-1232]

---

apps/@sparrow-desktop/src-tauri/src/main.rs

This fixes conditional mapping for titlebar-related changes in windows os.
No issue present
No known issues
Note: Keeping the PR small and focused makes it easier to review and merge. If you want to make multiple changes, please consider submitting them as separate pull requests.

fix: add conditional mapping for windows os

---

apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/plan.model.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/plan.model.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have added sparrow plans support for run history.
Fixes #jira

feat: sparrow plans run history support.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/services/ai-assistant.ws.service.ts
packages/@sparrow-common/src/dto/ai-assistant.ts

In this PR I have worked on AI rate limiting story , in this I have passed the required teamId to backend apis , mostly work is done in the backend PR .
[SPRW-1059]
[SPRW-1059]: https://techdome.atlassian.net/browse/SPRW-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Feat:Ai Rate Limiting [SPRW-1059]

---

packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/utils/index.ts
packages/@sparrow-workspaces/src/utils/mock-url-input-theme.ts

Add the static url in the mock request.

Add the static url in the mock request.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
packages/@sparrow-workspaces/src/utils/index.ts
packages/@sparrow-workspaces/src/utils/mock-url-input-theme.ts

feat: made mock base url static [SPRW-1250]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

Fixed the mock request url part for static url support 

fix: fixed the mock request url []

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts

I have updated the end point of admin panel.

fix: updated the admin panel direct link for payment.

---

packages/@sparrow-workspaces/src/features/ai-request-explorer/components/model-selector/ModelSectionInput.svelte

fix: AI request model selection dropdown fix

---

packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Disabled the AI debug button for guest users. Also fixed the UI

fix: disabled AI debug button for guest users & UI fix [SPRW-1303]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/run-history/RunHistory.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have added condition to support all the feature in sparrow edge. 
Fixes #jira

fix: sparrow edge issue for pop up.

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/adapter/team.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/repositories/team.repository.ts
packages/@sparrow-library/src/ui/toast/Toast.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-default/components/card/Card.svelte

Merge plans into development

---

apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

fix: creation of graphql request is creating ai request also-fixed

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

upgraded sparrow version to v2.26.0

feat: upgraded sparrow version to v2.26.0 []

---

.github/workflows/sparrow-app-development.yml

The deb build contained name as well as the version number, when hosted this would conflict when we want to give direct build link to the latest build.

fix: added fixed name for sparrow

---

packages/@sparrow-library/src/ui/options/Options.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/chat-conversations/ConversationHistoryItem.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/ai-request/AiRequest.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/mock-request/MockRequest.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/saved-request/SavedRequest.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte

fix: context menu offset from top and bottom dynamically [SPRW-102]
[SPRW-102]: https://techdome.atlassian.net/browse/SPRW-102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: context menu offset from top and bottom dynamically [SPRW-102]

---

packages/@sparrow-common/src/components/plan-upgrade-modal/PlanUpgradeModal.svelte

I have removed unwanted text.
Fixes #jira

fix: limit reach pop-up for a member UI issue SPRW-1339.

---

packages/@sparrow-workspaces/src/components/review-environment/ReviewEnvironment.svelte

feat: implement global environment override issue [SPRW-1393]
[SPRW-1393]: https://techdome.atlassian.net/browse/SPRW-1393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: implement global environment override issue [SPRW-1393]

---

packages/@sparrow-common/src/components/number-input/NumberInput.svelte
packages/@sparrow-library/src/ui/toggle/Toggle.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-responses-ratio/MockResponsesRatio.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte

In this pr, I have fixed the mock response ratios bugs.

Fix the ratios bug [SPRW-1370].

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts

I have added time stamp for rename of request in desktop as well.
Fixes #jira

fix: request rename issue in Global Search  SPRW-1334.

---

packages/@sparrow-library/src/forms/editor/theme.ts

I have updated the CSS for the theme in the editor.
Fixes #jira

Fix: placeholder position of multiple lines  SPRW-1073

---

packages/@sparrow-common/src/components/number-input/NumberInput.svelte

In this pr, I have fixed ratio bug related to weight value for the mock response.

Fix the ratios bug.

---

packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte

I have added the animation for tool tip for smooth transition.
Fixes #jira

feat: tool tip animation support SPRW-1348.

---

packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

In this pr, I have fixed the issue of opening of collection tab on click of arrow button.

Fix the opening of collection tab when click of arrow button.

---

packages/@sparrow-workspaces/src/features/ai-request-explorer/constants/FileUploadRestrictions.ts

Disaled the file search in anthropic.

diabled file search in anthropic providers

---

apps/@sparrow-desktop/src/constants/animation.ts
apps/@sparrow-desktop/src/pages/marketplace-page/MarketplacePage.svelte
apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
apps/@sparrow-web/src/constants/animation.ts
apps/@sparrow-web/src/pages/Teams/Teams.svelte
apps/@sparrow-web/src/pages/marketplace-page/MarketplacePage.svelte
packages/@sparrow-common/src/components/github-star-redirect/GithubStarRedirect.svelte
packages/@sparrow-common/src/components/index.ts
packages/@sparrow-common/src/components/lanuch-desktop/LanuchDesktop.svelte
packages/@sparrow-library/src/ui/modal/Modal.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

feat: Animation side nav transition page

feat: Animation side nav transition page

---

.github/workflows/sparrow-app-development.yml
.github/workflows/sparrow-app-prod.yaml

This PR adds support for the Mac App Store release.
It fixes nothing.
No known issues.

build: add support for mac app store build

---

apps/@sparrow-desktop/src/constants/animation.ts
apps/@sparrow-web/src/constants/animation.ts

fix: Revert request tab switch animation

fix: Revert request tab switch animation

---

packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte

In this pr, I have fixed the undefined value to response ratio.

Fix/undefined ratio bug.

---

.github/workflows/sparrow-app-prod.yaml

fix: update AWS S3 bucket and region for production release workflow

---

apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte

I have resolve the side bar closing issue in web app.
Fixes #jira

fix: sidebar closing issue in web app SPRW-1435.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

Resolved incorrect count issue caused by improper handling of async functions.
Fixes #jira

Fix: Testflow count issue on multiple clicks in the default workspace SPRW-1325.

---

apps/@sparrow-desktop/src/adapter/collection-tab.ts
apps/@sparrow-desktop/src/adapter/folder-tab.ts
apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/adapter/collection-tab.ts
apps/@sparrow-web/src/adapter/folder-tab.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/tab.model.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
packages/@sparrow-common/src/types/workspace/tab.ts
packages/@sparrow-common/src/utils/init-collection-tab.ts
packages/@sparrow-common/src/utils/init-folder-tab.ts
packages/@sparrow-common/src/utils/init-mock-request.ts
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte

In this pr, I have added the mock tag in folder which are present inside the mock collection.

Add mock tag in folder inside mock collection.

---

packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte

In this pr, I have fix the bug of mock tag.

Fix mock folder tag bug.

---

packages/@sparrow-workspaces/src/features/workspace-default/components/card/Card.svelte

I’ve updated the onClick handler to wait until the first task completes before proceeding.
Fixes #jira

fix: test flow multiple click issue on pop up SPRW-1325.

---

packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte

Resolved the issue where the initial view wasn’t closing for new users. The condition was incorrectly set to always open for first-time users.
Fixes #jira

fix: LHS panel collection test flow not closing new user issue SPRW-1437.

---

packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-library/src/ui/button/Button.svelte
packages/@sparrow-library/src/ui/keyboardShortcuts/keyboardShortcuts.svelte
packages/@sparrow-library/src/ui/options/Options.svelte
packages/@sparrow-workspaces/src/components/combo-text/ComboText.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-default-screen/ResponseDefaultScreen.svelte

I have added transition support for dropdown, options , command shortcuts and buttons. 
Fixes #jira

Feat: animation support for dropdown,options,shortcuts and button SPRW-1449.

---

packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte

feat: add expand behaviour to flatten collection [SPRW-1492]
[SPRW-1492]: https://techdome.atlassian.net/browse/SPRW-1492?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add expand behaviour to flatten collection [SPRW-1492]

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer-saved/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/request-body-navigator/RequestBodyNavigator.svelte

Removed code formatted notification 

fix: removed formatted notification []

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/MockHistroyExplorerPage/MockHistoryExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.svelte
apps/@sparrow-web/src/repositories/tab.repository.ts
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte

feat:  web app optimization for request items on rhs

feat:  web app optimization for request items on rhs

---

packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte

It resolved lag issue for empty folder.
Fixes #jira

fix: lag issue for empty folder SPRW-1428.

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/teams-page/sub-pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
packages/@sparrow-common/src/components/hub-payment-failed/HubPaymentFailed.svelte
packages/@sparrow-common/src/components/index.ts
packages/@sparrow-library/src/forms/multi-select/MultiSelect.svelte
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte

feat: implement team notifications [SPRW-1511]
[SPRW-1511]: https://techdome.atlassian.net/browse/SPRW-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: implement team notifications [SPRW-1511]

---

.github/workflows/sparrow-app-marketplace.yml
apps/@sparrow-desktop/src-tauri/Cargo.lock
apps/@sparrow-desktop/src-tauri/Cargo.toml

This PR fixes the app store testflight build.
NA
NA
No known issues

fix: app store build

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/CollectionAuthProfiles.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/sub-component/Rows/Row.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/sub-component/profile-actions/ProfileActions.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/sub-component/profile-auth-selector/ProfileAuthSector.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth/CollectionAuth.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

fix: fixed auth prfiles UI and functional issues

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/CollectionAuthProfiles.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/sub-component/Rows/Row.svelte

fix: fixed delay in UI while changing the default auth profile key [SPRW-1517]

---

packages/@sparrow-workspaces/src/features/collection-explorer/components/collection-auth-profiles/CollectionAuthProfiles.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/constants/description.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

fix: fixed LHS icons overriding issue on auth profile modal

---

.github/workflows/sparrow-app-prod.yaml

add msi and nsis in prod workflow

---

.github/workflows/sparrow-app-prod.yaml

add gpg in linux job prod workflow

---

.github/workflows/sparrow-app-prod.yaml

fix: windows build pipeline

---

.github/workflows/sparrow-app-prod.yaml

Release - 2.28.0

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/components/prompt-input/PromptInput.svelte

fix: env extraction for auth ai request

fix: env extraction for auth ai request

---

packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte

I have resolved the vertical scrolling issue of tab bar in mac using mouse.
Fixes #jira

fix: prevent vertical scrolling of tab bar issue for mac SPRW-1510.

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte

I have resolved the issue of the  rest explorer saved export issue.
Fixes #jira

fix: Rest Explorer saved export issue SPRW-1379.

---

packages/@sparrow-library/src/ui/tooltip/Tooltip.svelte

Resolved tooltip slide animation issue during position change.
Fixes #jira
https://github.com/user-attachments/assets/ca4e42d2-1f06-4d5f-b55d-ba4073f09dad

fix: tooltip slide animation positioning issue SPRW-1566.

---

apps/@sparrow-web/src/components/App.ts

In this PR i have fixed the issue where if guest user is enabled and user login so both sessions were mixing now if new login session is coming so old guest user session will automatically gets deleted. 

fix: fixed the guest user login issue [SPRW-1615]

---

apps/@sparrow-web/src/components/App.ts

Fixed the guest user bug where guest user session and new user session is getting mixed. 

patch: patch release for the trial flow

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
apps/@sparrow-web/src/pages/Teams/Teams.svelte

add the space

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-config-selection/AiConfigurations.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/chat-conversations/ConversationHistoryItem.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte

feat: implement variable in ai request

feat: implement variable in ai request

---

packages/@sparrow-workspaces/src/features/invite-to-workspace/components/invite-user-pickers/InviteUserPicker.svelte
packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte

I have added validation for email for invite workspace. 
Fixes #not available.

fix: added validation for email for invite workspace SPRW-1498.

---

packages/@sparrow-library/src/forms/select/Select.svelte

I have resolved tool tip issue in AI chatbot,
Fixes #not_available

fix: Prompt Input tool tip issue in AI chatbot.

---

packages/@sparrow-workspaces/src/features/ai-request-explorer/components/generate-prompt/GeneratePrompt.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
packages/@sparrow-workspaces/src/features/hub-explorer/layout/HubExplorer.svelte

fix the responsiveness bugs [SPRW-1633].

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/repositories/collection.repository.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/repositories/collection.repository.ts
packages/@sparrow-workspaces/src/components/test-flow-bottom-panel-navbar/TestFlowBottomPanelNavbar.svelte

fix: api caching for testflow response [SPRW-1634]
[SPRW-1634]: https://techdome.atlassian.net/browse/SPRW-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: api caching for testflow response [SPRW-1634]

---

packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte

fix: fixed the placeholder size [SPRW-614]

---

packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte

I have fixed the AI request count issue in folder delete modal.
Fixes #jira

fix: AI request count issue in folder delete popup SPRW-1593.

---

apps/@sparrow-desktop/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/EnvironmentPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte

Resolved the issue with environment deselection during deletion.
Fixes #jira
https://github.com/user-attachments/assets/f01b6b9f-987d-4504-b787-2b4c2eea8209

fix: deselecting while deleting a environment issue SPRW-640.

---

packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte

Currently, users are able to update the connection URL even after the WebSocket is established. This behavior is not intended — the URL should only be updatable when the connection is either disconnected or in a ‘ready to connect’ state. I’ve updated the implementation accordingly.
Fixes #jira
https://github.com/user-attachments/assets/9c06a49e-bd6a-4b5e-b12f-cfdf93214e1a

fix: WebSocket connected input URL issue SPRW-755.

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte

I’ve updated it to set the team ID based on the workspace the user is trying to switch.
Fixes #jira
https://github.com/user-attachments/assets/7f3805f8-1acd-4d41-823d-1f723eb75977

fix: Global search switching hub issue SPRW-883.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte

In this pr, I have fixed the tooltip bugs issue for mock url.

Fix tooltip bugs.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

I have updated the folder tab type while we are creating a folder.
Fixes #jira

Fix: folder creation tab issue SPRW-1083.

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
apps/@sparrow-web/src/pages/Teams/Teams.svelte

I have corrected the position of trail button according to the alignment of the other buttons.
Fixes #jira

fix: trial plan button position issue SPRW-705.

---

packages/@sparrow-common/src/components/header/sub-component/UserProfileModal.svelte
packages/@sparrow-common/src/utils/init-ai-request-tab.ts
packages/@sparrow-library/src/forms/select/Select.svelte
packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
packages/@sparrow-library/src/ui/options/Options.svelte
packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/components/environment-picker/EnvironmentPicker.svelte
packages/@sparrow-workspaces/src/components/missed-environment/MissedEnvironment.svelte
packages/@sparrow-workspaces/src/components/review-environment/ReviewEnvironment.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/ai-request-chatbot/layout/ChatBot.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/components/generate-prompt/GeneratePrompt.svelte
packages/@sparrow-workspaces/src/features/ai-request-explorer/layout/AiRequestExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/utils/prompt-input-theme.ts
packages/@sparrow-workspaces/src/utils/text-editor-theme.ts

feat: add ai request issues [SPRW-1628]
[SPRW-1628]: https://techdome.atlassian.net/browse/SPRW-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add ai request issues [SPRW-1628]

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-status/ResponseStatus.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/test-flow-bottom-panel/TestFlowBottomPanel.svelte

Tooltip overlapping is observed in rest API and test flow section
Tooltip overlapping is observed in rest API and test flow section

fix:Tooltip overlapping is observed in rest API and test flow section

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts

I have resolved the folder issue for default collection dropdown select option as well.
Fixes #jira

fix: folder issue from default collection dropdown SPRW-634.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/AiRequestExplorerPage/AiRequestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts

Implement sentry logs in AI Chatbot Socket Connection

implement sentry logs in ai chatbot

---

.github/workflows/sparrow-app-marketplace.yml
.github/workflows/sparrow-app-prod.yaml
.husky/pre-commit
package.json

remove sync version

---

.github/CODEOWNERS
apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/Cargo.lock
apps/@sparrow-desktop/src-tauri/Cargo.toml
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: upgrade app version to 2-28-2

feat: upgrade app version to 2-28-2

---

.github/workflows/sparrow-app-development.yml
.github/workflows/sparrow-app-prod.yaml

feat: remove packages on pre commit

feat: remove packages on pre commit

---

apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/environment-tab.model.ts
apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/database/database.ts
apps/@sparrow-web/src/models/tab.model.ts

I have added migration function to update items in Rxdb.
Fixes #jira

fix: generate variable Rxdb update.

---

package.json
packages/@sparrow-library/src/forms/editor/theme.ts
yarn.lock

feat: SPRW-1709 user can disable JSON in input param by commenting

feat: SPRW-1709 user can disable JSON in input param by commenting

---

package.json
yarn.lock

Updated json5 package version to 1.0.3, to resolve the build failure issue. 

fix: updated the codemirror-json5 packager version [SPRW-1706]

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
packages/@sparrow-library/src/icons/ArrowHookRegular.svelte
packages/@sparrow-library/src/icons/SparkleFilled.svelte
packages/@sparrow-library/src/icons/index.ts
packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte

SPRW-1737 [Generated Variable] Save flow

feat: SPRW-1737 [Generated Variable] Save flow

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte

I’ve added a condition to enable or disable the generate feature based on tab generate variable field. Additionally, the feature is hidden for guest users, and I’ve implemented a redirect to the documentation.
Fixes #jira

fix: generate variable conditions.

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/environment-explorer/components/apply-generated-variables/ApplyGeneratedVariables.svelte
packages/@sparrow-workspaces/src/features/environment-explorer/components/index.ts
packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte
packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte

Sprw 1737 generated variable variables added succefully

Sprw 1737 generated variable variables added succefully

---

apps/@sparrow-desktop/src/constants/constants.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
apps/@sparrow-web/src/constants/constants.ts

Sprw 1653 generate variables accept all buttons

Sprw 1653 generate variables accept all buttons

---

packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

I have added the condition for the generate variables no allow to click when the user is viewer role, along with the undo delete option with automatically delete after 10 secs.
Fixes #jira
https://github.com/user-attachments/assets/11c6080f-eb04-45be-8cad-70e344527632

feat: generate variable restrictions along with undo for generate variables SPRW-1762.  

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte

Remove content type from header in curl import.

---

packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

I have added condition it will only display for collection.
Fixes #jira

fix: generate button issue.

---

packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

I have corrected the generate variable button.
Fixes #jira

fix: condition of generate variable button.

---

package.json
packages/@sparrow-workspaces/src/features/rest-explorer/utils/decode-request.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/utils/decode-testflow.ts

fix: json5 parser

---

packages/@sparrow-workspaces/src/features/environment-explorer/components/apply-generated-variables/ApplyGeneratedVariables.svelte

SPRW-1792 Issues in generate variable

SPRW-1792 Issues in generate variable

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/generate-variables/components/GenerateVariablesLoading.svelte
packages/@sparrow-workspaces/src/features/generate-variables/layout/GenerateVariable.svelte

I have fixed the generate variable Ui bugs.
Fixes #jira

fix: generate variable UI bugs SPRW-1791.

---

docker-compose.yml

fix: port mapping

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/Cargo.lock
apps/@sparrow-desktop/src-tauri/Cargo.toml
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat app version upgrade v-29-0

feat app version upgrade v-29-0

---

apps/@sparrow-web/src/components/App.svelte

feat: log constants

---

packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

fix:Collection name exceeds character limit but still gets accepted

fix:Collection name exceeds character limit but still gets accepted

---

packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte

fix: SPRW-1835 In websocket,socket.io-"No result found" is misplaed

fix:SPRW-1835 In websocket,socket.io

---

packages/@sparrow-workspaces/src/components/combo-text/ComboText.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte

fix:Sprw 1509 animation glitch in rest api shortcut section 

fix:Sprw 1509 animation glitch in rest api shortcut section

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts

Remove headers only for content-type form data.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
packages/@sparrow-support/src/components/Attachment/Attachment.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte

fix: Multiple bugs in ticket no 439,635,1139 

fix: Multiple bugs in ticket no 439,635,1139

---

packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte

fix:User is able to add extra variable in generate variable section and not able to remove it

fix:User is able to add extra variable in generate variable section and not able to remove it

---

packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

removed help me debug from public workspace as it should not be available for the users in public workspace whom they are not part of. 

fix: removed help me debug from public workspace [SPRW-1787]

---

packages/@sparrow-common/src/types/workspace/ai-request-base.ts
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

Added alias for AI request and fixed the request toast notification. 

fix: fixed request text issue in AI Request saved operation [SPRW-1730]

---

packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

fix:On 14-inch Windows Device, the Test Flow icon is not displayed properly on the desktop application.

fix:On 14-inch Windows Device, the Test Flow icon is not displayed properly on the desktop application.

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte

In this pr, I have added changes for the merge body in web.

Fix the merge body changes on switching tabs.

---

packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte
packages/@sparrow-common/src/features/create-team/constants/name.ts
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-name/UpdateTeamName.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte

In this pr, I have fixed the regex function to validate the correct team and workspace name.

Fix the regex function to validate the correct team and workspace name.

---

packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte

Removed input class on focus for mock collection description. 

fix: removed focus class from input [SPRW-1732]

---

apps/@sparrow-desktop/src-tauri/tauri.conf.json

This PR aims to fix the deep link redirection issue in the Windows build.
NA
NA
No known issues

fix: deep link in windows build

---

packages/@sparrow-workspaces/src/features/collection-list/components/ai-request/AiRequest.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte

fix:Sprw 1802 alignment issues observed in url use variables

fix:Sprw 1802 alignment issues observed in url use variables

---

packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
packages/@sparrow-common/src/features/create-team/constants/icon.ts
packages/@sparrow-common/src/features/create-team/types/form.ts
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
packages/@sparrow-teams/src/features/team-settings/constants/team-profile.ts
packages/@sparrow-teams/src/features/team-settings/types/team-profile.ts

fix:SPRW-1827 Prevent Pixel Flood Attack via Image Uploads 

fix:SPRW-1827 Prevent Pixel Flood Attack via Image Uploads

---

packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte

During long conversations, we noticed a delay that increased with the message index. Even after the content was loaded, it appeared late. I've now optimized that behavior.
Fixes #jira

fix: AI chat bot interface rendering issue SPRW-1302.

---

packages/@sparrow-common/src/utils/formatTime.ts
packages/@sparrow-support/src/components/CommentCard.svelte

fix: negative time issue

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/no-code/NoCode.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/no-code/sub-components/test-list-item/TestListItem.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
packages/@sparrow-workspaces/src/hoc/WithSelectV4.svelte

Sprw 1864 assertions no code test cases no code flow setup

Sprw 1864 assertions no code test cases no code flow setup

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body/ResponseBody.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-test-results/ResponseTestResults.svelte

Added test cases response tab and filter options. 

feat: added response test result UI section [SPRW-1858]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts

current after data inserting we should be in unsaved state,  
Fixes #jira

fix: generate mock data issue while update.

---

packages/@sparrow-library/src/ui/badge/Badge.svelte
packages/@sparrow-library/src/ui/navigator/Navigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Added new badge type for response test results 

feat: added new badge type for test results [SPRW-1858]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts

feat: duplicate tests for request tab

feat: duplicate tests for request tab

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte

fix:Sprw 1861 the insert changes is not working in desktop app

fix:Sprw 1861 the insert changes is not working in desktop app

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/utils/common-snippets.ts

This Pr contains the assertion of script part setup.
Fixes #jira

feat: assertion setup for script SPRW-1924.

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/RequestBody.svelte

fix: mock data issue (temporary fix)

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-desktop/src/services/ai-assistant.service.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-web/src/services/ai-assistant.service.ts
packages/@sparrow-common/src/dto/ai-assistant.ts
packages/@sparrow-common/src/utils/init-request-tab.ts
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-test-results/ResponseTestResults.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

feat: assertions script mode script error

feat: assertions script mode script error

---

packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/utils/common-snippets.ts

I have updated the assertion snippets with JavaScript error syntax management.
Fixes #jira

feat: assertion snippets with JavaScript editor syntax error support. SPRW-1925

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
package.json
yarn.lock

feat: add xml testcases parser [SPRW-1929]
[SPRW-1929]: https://techdome.atlassian.net/browse/SPRW-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add xml testcases parser [SPRW-1929]

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte

I have updated search snippets according to the figma. 
Fixes #jira

fix: assertion script LHS panel search update SPRW-1924.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte

react state is always overwriting the exist the value and making it undefined, wrong way of declaration.
Fixes #jira

fix: AI chat data missing issue SPRW-2027. 

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.svelte
packages/@sparrow-workspaces/src/features/request-tab-tour-guide/utils/requestTabScriptCardPositions.ts
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

I have function passing is wrong for desktop.
Fixes #jira

fix: assertion tour guide for desktop issue SPRW-1921.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/workers/test-script-worker.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/workers/test-script-worker.ts

feat: add webworker for test execution

feat: add webworker for test execution

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/RequestTests.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Fix/generate ai test bug.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
packages/@sparrow-library/src/forms/editor/editor.ts
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-test-results/ResponseTestResults.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

Fix: webworker path

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/Cargo.lock
apps/@sparrow-desktop/src-tauri/Cargo.toml
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Add build for test.

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte

Fix the overlapping issue in the input box.

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte

Fix UI bugs.

---

packages/@sparrow-common/src/features/create-team/components/team-name/TeamName.svelte

I have correct the implementation of validation for hub name while creating a new one. 
Fixes #jira

fix: validation check for hub name SPRW-1910. 

---

apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
apps/@sparrow-desktop/src/services/ai-assistant.ws.service.ts
apps/@sparrow-desktop/src/services/auth.service.ts
apps/@sparrow-desktop/src/services/collection.ts

feat: add desktop support [SPRW-1975]
[SPRW-1975]: https://techdome.atlassian.net/browse/SPRW-1975?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add desktop support [SPRW-1975]

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte

Fixed snippets vertical text alignment when in its collapsed state.
Fixes #2064 

bug: Fix snippets vertical text alignment[1924]

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.svelte
packages/@sparrow-common/package.json
packages/@sparrow-common/src/types/workspace/tab.ts
packages/@sparrow-common/src/types/workspace/testflow-schedule-tab.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-common/src/utils/init-testflow-schedule-tab.ts
packages/@sparrow-workspaces/src/features/index.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/history-table/HistoryTable.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/history-table/sub-component/history-table-expanded/HistoryTableExpanded.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/index.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/schedule-navigator/ScheduleNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/TestResults.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/index.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/index.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/types/api-history.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/types/index.ts

feat: set schedule view and manage scheduled runs

feat: set schedule view and manage scheduled runs

---

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-tests/sub-components/script/Script.svelte

Reverts sparrowapp-dev/sparrow-app#3843

Revert "bug: Fix snippets vertical text alignment[1924]"

---

apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.svelte
apps/@sparrow-web/src/models/tab.model.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowScheduleRVExplorerPage.svelte/TestflowScheduleRVExplorerPage.svelte
packages/@sparrow-common/src/factory/init-tab.ts
packages/@sparrow-common/src/types/workspace/tab.ts
packages/@sparrow-common/src/types/workspace/testflow-schedule-run-view-tab.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-common/src/utils/init-testflow-schedule-run-view-tab.ts
packages/@sparrow-workspaces/src/features/index.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/TestResults.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/index.ts
packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/layout/TestflowScheduleRVExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/layout/index.ts

I have setup the new tab for viewing the result of schedule runs 
Fixes #jira

feat: test flow schedule run view SPRW-2129.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/TestResults.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/test-results/sub-components/Result.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte

feat: add testflow schedule run and delete feature

feat: add testflow schedule run and delete feature

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/components/schedule-row/ScheduleRow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte

In this pr, I have added the fucntiaonlity of persisting the state of save button.

Add schedule run functionality.

---

packages/@sparrow-common/src/features/schedule-run-pop-up/layout/ScheduleRunPopUp.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte

fix the environment select

---

packages/@sparrow-common/src/features/schedule-run-pop-up/layout/ScheduleRunPopUp.svelte
packages/@sparrow-common/src/utils/extractTimefromISO.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte

Use the utc format for daily and weekly.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts

I have fixed the issue of response. 
Fixes #jira

fix: test flow response formatting issue. 

---

apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts

I have add the path for event capture of post hog events.
Fixes #jira

fix: event capture path missing.

---

packages/@sparrow-common/src/features/schedule-run-pop-up/layout/ScheduleRunPopUp.svelte
packages/@sparrow-common/src/utils/extractTimefromISO.ts
packages/@sparrow-common/src/utils/formatDays.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/layout/TestflowScheduleExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-schedule-run-view-explorer/layout/TetsflowScheduleRunViewExplorer.svelte

Fix the date converter and time converter

---

packages/@sparrow-workspaces/src/features/testflow-schedule-explorer/components/configurations/Configurations.svelte

fix the save changes

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowScheduleExplorerPage/TestflowScheduleExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

I have corrected all the post hog events with there properties.
Fixes #jira

fix: post hog events properties issue SPRW-2149.

---

packages/@sparrow-library/src/forms/label-field/LabelField.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

I have resolved UI issue of members visibility and delete modal label text. 
Fixes #jira

fix: hub UI issues SPRW-1937.
