.github/pull_request_template.md

Please do not leave this blank 
This PR [adds/removes/fixes/replaces] the [feature/bug/etc].

docs: readme fix & pull request template

---

README.md
docs/CODEOWNERS.md

This PR adds the CODEOWNER.md file

docs: add CODEOWNERS.md []

---

src/lib/components/workspace/members/Members.svelte

Implement search functionality to filter out members in a team.

feat: Implement search functionality to filter members in a team

---

src/lib/components/Modal/MemberChangeRolePopup.svelte
src/lib/components/Modal/RemoveConfirmationPopup.svelte
src/lib/components/workspace/team-invite-popup/TeamInvitePopup.svelte

This PR resolves the issue for Custom Button, which was imported as CoverButton.svelte.
I tried building it up locally, and it worked also the functionalities are working as well.
SP-438

fix: custom button error

---

.github/workflows/release.yaml
package.json

Please do not leave this blank 
- [] 👍 yes
- [] 👍 yes

feat: created release.yaml[1]

---

src/pages/Collections/Collections.svelte

enable environment re-renders while switching between tabs
Fixes issue #114

fix: enable environment re-renders while switching between tabs

---

src/App.svelte
src/lib/components/environments/environments-list/sub-components/environment-tab/EnvironmentTab.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.svelte
src/lib/components/workspace/workspace-tab/myWorkspace.svelte
src/lib/components/workspace/workspaceSidebar.svelte

1) Fix incorrect profile-icon first letter.
2) Fix window was not draggable from header free space when window is shrinked.
3) Fix environment right click menu.

fix: profile-icon first letter, drag from header free space when window is shrinked

---

src/lib/components/environments/enviroments-panel/EnvironmentPanel.svelte
src/lib/components/environments/environments-list/EnvironmentList.svelte
src/pages/Environment/Environment.svelte

Handle screen flicker environment  
Fixes issue #48

fix: handle screen flicker environment  

---

src/lib/components/Modal/InvalidSyntaxPopup.svelte
src/lib/components/collections/collections-list/ImportCollection.svelte
src/lib/components/inputs/FileInput.svelte
src/pages/Teams/Teams.svelte

enable drag and drop feature for import collection
Fixes issue #112

feat: enable drag and drop feature for import collection

---

src/App.svelte
src/lib/components/workspace/member-worspace/MemberWorkspace.svelte
src/pages/Auth/forgot-password/ForgotPassword.svelte
src/pages/Auth/login-page/LoginPage.svelte

This PR fixes the login loader issue. It also disables auto-capitalize during login and forgot password which was causing issues of email not getting sent on forgot password.

fix: login loader appearing even on login form validation errors[]

---

.github/workflows/release.yaml
src-tauri/tauri.conf.json

feat: release[]

---

src/lib/components/workspace/members/Tile.svelte

feat: User Info Modal

---

src/lib/components/dashboard/card/Card.svelte
src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte

refactor: Added generic card [#138]

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte
src/lib/components/dashboard/teams/TeamsList.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/env-value/EnvValue.svelte
src/lib/components/environments/environments-list/EnvironmentList.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.svelte
src/lib/components/list/List.svelte
src/lib/components/sidebar/Sidebar.svelte
src/lib/components/tooltip/Tooltip.svelte
src/lib/components/workspace/workspace-list/WorkspaceList.svelte

Generic tooltip component
Fixed issue #137

feat: Generic tooltip component

---

src/lib/components/Transition/FetchDataProgressBar.svelte
src/lib/components/Transition/SyntaxCheckProgressBar .svelte
src/lib/components/Transition/progress-bar/ProgressBar.svelte
src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/styles/style.scss

create generic progress bar
Fixes issue #141

refactor: create generic progress bar

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/req-res-section/SidebarRight.svelte
src/lib/components/dropdown/EnvironmentDropdown.svelte
src/lib/components/environments/environments-list/EnvironmentList.svelte
src/pages/Environment/Environment.svelte

fix: Added missing mixpanel events []

---

src/lib/components/collections/collection-tab/MyCollection.svelte
src/lib/components/collections/collection-tab/MyCollection.viewModel.ts
src/lib/components/collections/folder-tab/MyFolder.viewModel.ts
src/lib/components/collections/req-res-section/sub-components/sub-components-header/ApiSendRequestPage.ViewModel.ts
src/lib/utils/dto/collection.ts

This pr fixes the scenario where a env variable contains http/s.

fix: env containing http/s not working[#223]

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/workspace/WorkspaceContent.svelte
src/lib/repositories/team.repository.ts
src/pages/Teams/Teams.svelte
src/pages/Teams/team.viewModel.ts

This PR fixes the below bug, 
Old team name appearing on new team creation.

fix: team name not updating on new team creation[]

---

src/lib/components/collections/collection-tab/MyCollection.viewModel.ts
src/lib/components/collections/folder-tab/MyFolder.viewModel.ts

Fix - Collection description not updating.

fix: collection description not updating[]

---

src/pages/Teams/Teams.svelte

This PR fixes loading loop on leave button when clicked on it.

fix: handle leave team scenario[#180]

---

src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/pages/Auth/login-page/login-page.ts

In This PR i have fixed the navigation issue where we login we will redirected to Home tab instead of Collection tab. 
Secondly I have fixed the issue in workspace list(grid view) when we directly jump to last we used to see a blank page but now we will see workspace cards their.

fix: Fix workspace list and navigation on login

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/dashboard/recent-workspace/RecentWorkspace.svelte
src/lib/components/dashboard/rows/Rows.svelte
src/lib/components/dashboard/teams/TeamsList.svelte
src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/dashboard/workspaces/AllWorkspace.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.ViewModel.ts
src/lib/components/header/header-dashboard/HeaderDashboardDropdown.svelte
src/lib/components/workspace/WorkspaceContent.svelte
src/lib/components/workspace/workspace-list/WorkspaceList.svelte
src/lib/repositories/team.repository.ts
src/lib/store/team.store.ts
src/pages/Teams/Teams.svelte

1. fix logo break on teams navigation
2. Svelte store removed and app connected to team model directly. earlier data is not persistent. and showing inconsistent data because we used store and local db both to achieve a single operation.
Fixes issue #186

fix: logo break on teams navigation

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/req-res-section/sub-components/request-body-section/RequestBody.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/CodeMirrorInput.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/InputEditorTheme.ts
src/lib/components/editor/CodeMirrorResponse.svelte
src/lib/components/key-value/KeyValue.svelte
src/lib/components/key-value/KeyValueFile.svelte

refactor: Refactored key value pair component [131]

---

src/lib/components/collections/collection-tab/MyCollection.svelte
src/lib/components/collections/folder-tab/MyFolder.svelte

Refresh api and folder count at collection and folder level
Fixes issue #277

feat: Refresh api and folder count at collection and folder level

---

src/lib/components/environments/enviroments-panel/EnvironmentPanel.svelte
src/lib/components/environments/enviroments-panel/sub-components/quick-help/QuickHelp.svelte
src/lib/utils/constants/environment.constant.ts

fix: question mark button for environment quick help
Fixes issue #157
Fixes issue #158

fix: question mark button for environment quick help

---

src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte

This PR fixes the search in workspaces. Even if partial search string is given, you will get the related results.
Example: 
search string - space
result - My Workspace, Spaceship, Your Workspace

fix : workspace search[298]

---

src/lib/components/dashboard/rows/Rows.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/dashboard/workspaces/AllWorkspace.svelte

fix: workspace dropdown spelling[closes #297]

---

src/lib/components/env-value/EnvValue.svelte

fix: closes #295

---

src/lib/components/collections/collection-tab/MyCollection.svelte
src/lib/components/collections/folder-tab/MyFolder.svelte
src/lib/components/workspace/workspace-tab/myWorkspace.svelte

fix: Closes #294 Closes #293 Closes #289

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte
src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/lib/components/workspace/WorkspaceContent.svelte
src/lib/components/workspace/team-invite/TeamInvite.svelte
src/lib/utils/workspacetimeUtils.ts
src/pages/dashboard/Dashboard.svelte
src/styles/style.scss

1) Fixes #257 
2) Fixes #254 
3) Fixes #235 
4) Fixes #231 
5) Sets workspace grid page to 1 when team is toggled.

fix: workspace grid for non admin[257]

---

.github/workflows/pr-release.yaml
src-tauri/gen/schemas/windows-schema.json

feat: update-pr-release.yaml file[]

---

src/lib/components/collections/req-res-section/sub-components/request-authorization-section/BearerToken.svelte
src/lib/components/workspace/workspace-tab/myWorkspace.svelte

fix: auth bearer token textarea height[282]

---

src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte

fix: text center added to buttons[262]

---

src/lib/components/Modal/InviteToWorkspace.svelte
src/lib/components/dropdown/Dropdown.svelte

fix: header dropdown breaking in long texts[#281]

---

src/lib/components/collections/collections-list/CollectionList.svelte

fix: no results found handle on api search[47]

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
yarn.lock

This PR adds deep link for windows necessary for browser based auth aka Auth V2.

feat: deep link for windows[]

---

src/lib/components/workspace/WorkspaceContent.svelte
src/pages/Teams/Teams.svelte

fix: leave team toggle button 
Fixes issue #265

fix: leave team toggle button 

---

.github/workflows/pr-release.yaml

feat: update pr-release.yaml file[]

---

src-tauri/assets/DeepLinkRegistryEntries.wxs

fix: path change[]

---

src-tauri/tauri.conf.json
src/lib/components/collections/req-res-section/sub-components/response-body-section/DefaultPage.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/ApiSendRequestPage.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/Tab.svelte
src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte

fix: Fixed UI Bugs and min window width []

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte
src/lib/components/dropdown/Dropdown.svelte

fix: Solved UI Bugs []

---

src/lib/assets/refresh.svg
src/lib/components/collections/collections-list/collection/Collection.svelte
src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.svelte
src/lib/components/workspace/workspaceSetting.svelte
src/lib/services-v2/common.service.ts

1. added active sync partial ui based on feature flag 
2. fixed bugs: 
https://github.com/sparrowapp-dev/sparrow-app/issues/109
https://github.com/sparrowapp-dev/sparrow-app/issues/2
- [ y] 🍕 Feature
- [ y] 🐛 Bug Fix
- [y ] 👍 yes

fix #109 #2 and activesync

---

src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/lib/components/workspace/workspaceSetting.svelte

fixed :
https://github.com/sparrowapp-dev/sparrow-app/issues/363
https://github.com/sparrowapp-dev/sparrow-app/issues/361

#361 and #363

---

src/App.svelte

build: trigger test build[]

---

.github/workflows/pr-release.yaml

Description :-
Add auth and sender email env in release yaml

build: add auth and sender email env in release yaml

---

src/pages/Auth/entry-point/EntryPoint.svelte

fix: sparrow auth url[]

---

src/App.svelte
src/lib/components/collections/collections-list/request/Request.svelte
src/lib/components/collections/collections-list/searchTree/Request.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/CodeMirrorInput.svelte
src/lib/components/dashboard/workspace-card-list/WorkspaceCardList.svelte
src/lib/components/dropdown/Dropdown.svelte
src/lib/components/header/global-search-bar/GlobalSearchBar.svelte

fixed :
https://github.com/sparrowapp-dev/sparrow-app/issues/47
https://github.com/sparrowapp-dev/sparrow-app/issues/1
https://github.com/sparrowapp-dev/sparrow-app/issues/207

fix multiple bugs #1 #47 #204

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/ApiSendRequestPage.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/CodeMirrorInput.svelte

fixed :
https://github.com/sparrowapp-dev/sparrow-app/issues/225

fix bug #225

---

src/lib/components/workspace/workspaceSetting.svelte
src/lib/components/workspace/workspaceUserInfo.svelte

Fixes issue #274 
Fixes issue #273

fix: workspace modal toggle on every click 

---

src/lib/components/workspace/member-worspace/MemberWorkspace.svelte

fix admins text on change member dropdown
Fixes issue #272

fix: admins text on change member dropdown

---

.github/workflows/development.yaml

feat: created development.yaml file which trigered on pull request[]

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/CodeMirrorInput.svelte

Added tooltip on hover for env variables

fix: Added hover tooltip for available envs []

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/workspace/workspace-tab/myWorkspace.svelte
src/lib/repositories/workspace.repository.ts

fix: dropdown symmetry [#272]

---

package.json
src-tauri/tauri.conf.json
src/pages/Auth/entry-point/EntryPoint.svelte

Added app version on the landing screen.

feat: add version on landing screen[]

---

src/lib/components/header/global-search-bar/GlobalSearchBar.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.svelte

shift global search to center 
Fixes issue #243

fix: shift global search to center 

---

package.json
src-tauri/tauri.conf.json

auto update test version downgrade.

build: version - 0.0.0[]

---

package.json
src-tauri/tauri.conf.json

build: version - 1.0.0[]

---

src/lib/components/collections/collections-list/ImportCollection.viewModel.ts
src/lib/components/collections/collections-list/collection/collection-utils/utils.ts
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/services/collection.service.ts

active sync merge

---

src-tauri/tauri.conf.json

feat: add dev updater url[]

---

package.json
src-tauri/tauri.conf.json
src/lib/components/Modal/AutoUpdateDialog.svelte

feat: remove auto relaunch after update[]

---

src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte

checked value

---

.github/workflows/development.yaml
package.json
src-tauri/tauri.conf.json
src/lib/components/Modal/AutoUpdateDialog.svelte
src/lib/components/dashboard/rows/Rows.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/workspace/workspace-tab/myWorkspace.svelte
src/lib/components/workspace/workspaceSetting.svelte

Feat: onboarding v2

---

.github/workflows/development.yaml
package.json
src-tauri/tauri.conf.json

build: 0.0.0[]

---

.github/workflows/development.yaml
package.json
src-tauri/tauri.conf.json

build: 1.0.0[]

---

src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/workspace/workspace-tab/myWorkspace.svelte
src/lib/repositories/workspace.repository.ts
src/pages/dashboard/Dashboard.svelte

fix collection list rerenders on sparrow home tab

fix collection list rerenders on sparrow home tab

---

src/App.svelte
src/lib/components/collections/collections-list/CollectionList.ViewModel.ts
src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/collections-list/collection/Collection.svelte
src/lib/components/collections/collections-list/folder/Folder.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/database/app.database.ts
src/lib/models/collection.model.ts
src/lib/repositories/collection.repository.ts

implement refresh collection active sync

feat: implement refresh collection active sync 

---

src-tauri/assets/CleanupOnUninstall.wxs
src-tauri/gen/schemas/windows-schema.json
src-tauri/tauri.conf.json

This PR fixes the issue of local state on resetting on app uninstall.

fix: windows local app data cleanup on app uninstall[]

---

src/pages/dashboard/Dashboard.svelte

fix sidebar color change rerenders

fix sidebar color change rerenders

---

src-tauri/tauri.conf.json

feat: workspace specific tabs[]

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/TabBar.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte

fix: handle delete workspace []

---

src/lib/api/api.common.ts
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/workspace/workspaceSetting.svelte
src/lib/database/app.database.ts
src/lib/repositories/team.repository.ts

This PR replaces spaces with %20 giving support for query params with spaces.

fix: handle spaces in http request[]

---

src/App.svelte
src/lib/components/header/header-dashboard/HeaderDashboardDropdown.svelte
src/lib/components/workspace/WorkspaceContent.svelte
src/lib/repositories/team.repository.ts
src/lib/utils/helpers/common.helper.ts
src/pages/Teams/Teams.svelte

fix: teams delete shows blank screen

fix: teams delete blank screen 

---

src/lib/components/Modal/MemberChangeRolePopup.svelte
src/lib/components/collections/collections-list/collection/Collection.svelte
src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/lib/components/workspace/members/Tile.svelte
src/lib/components/workspace/workspaceSetting.svelte

This PR fixes 
1) Team name check if it contains right quotation mark instead of single quote.
2) Open collection button on right click

fix: team name check and open collection[]

---

.github/workflows/release.yaml
package.json
src-tauri/tauri.conf.json

feat: updated env and release.yaml[]

---

package.json

Set repo to private to avoid semantic release error[]

chore: set repo to private to avoid semantic release error[]

---

package.json

Release 1.1.0 - semantic release fix

---

.github/workflows/development.yaml

feat: changes made in  development.yml file[]

---

.github/workflows/development.yaml

Added New env

---

src/lib/components/workspace/WorkspaceContent.svelte
src/lib/repositories/team.repository.ts
src/lib/repositories/workspace.repository.ts
src/pages/Teams/Teams.svelte
src/pages/Teams/team.viewModel.ts
src/pages/dashboard/Dashboard.svelte

Fix: blank screen issue on leave team

Fix: blank screen issue on leave team

---

src/lib/components/environments/enviroments-panel/sub-components/quick-help/QuickHelp.svelte

fix: remove sensitive information from quick help 
Fixes issue #474

fix: remove sensitive information section from quick help 

---

src/lib/components/collections/req-res-section/sub-components/request-body-section/RequestParam.svelte
src/lib/components/collections/req-res-section/sub-components/response-body-section/ResponseBody.svelte
src/lib/components/collections/req-res-section/sub-components/response-body-section/ResponseParams.svelte
src/lib/components/editor/CodeMirrorResponse.svelte
src/lib/components/editor/codeMirrorTheme.ts
src/lib/utils/constants/fonts.constant.ts

Fixed the issue of content load when response is too long and also changed the font size and family

fix: Fix code mirror long content load issue and font []

---

src-tauri/tauri.conf.json

Update to generic updater url to be later changed in Github Action.

chore: add generic updater endpoint variable[]

---

.github/workflows/development.yaml

feat: Api identifier endpoint change in development.yml file[]

---

.github/workflows/development.yaml

feat: made changes in development.yml file[]

---

src/lib/components/Modal/Modal.svelte
src/lib/components/workspace/members/Tile.svelte
src/lib/utils/constants.ts

fix: Minor UI Changes []

---

.github/workflows/development.yaml
.github/workflows/release.yaml
package.json

feat: changes made in release.yaml[]

---

.github/workflows/release.yaml

fix release pipeline for apple build notarize

build: apple notarize[]

---

src/lib/components/workspace/workspaceSetting.svelte

deleted workspace popup wont show current worlkspace

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/collections-list/collection/Collection.svelte
src/lib/components/collections/collections-list/empty-collection/EmptyCollection.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/collections/req-res-section/sub-components/request-body-section/RequestBody.svelte
src/lib/components/collections/req-res-section/sub-components/request-body-section/RequestParam.svelte
src/lib/components/collections/req-res-section/sub-components/response-body-section/ResponseBody.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/ApiSendRequestPage.svelte
src/lib/components/dashboard/teams/TeamsList.svelte
src/lib/components/editor/CodeMirrorResponse.svelte
src/lib/components/environments/enviroments-panel/EnvironmentPanel.svelte
src/lib/components/environments/environments-list/EnvironmentList.svelte
src/lib/components/tooltip/Tooltip.svelte
src/lib/components/workspace/WorkspaceContent.svelte
src/lib/components/workspace/workspace-list/WorkspaceList.svelte
src/lib/store/collection.ts
src/lib/store/environment.ts
src/lib/store/workspace.store.ts
src/pages/Collections/Collections.svelte
src/pages/Environment/Environment.svelte
src/pages/Teams/Teams.svelte
src/styles/style.scss

enhance ui based on internal demo feedback

feat: enhance ui based on internal demo feedback

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/collections-list/collection/collection-utils/utils.ts
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/dropdown/Dropdown.svelte

feat: implement import collection UI 

---

src-tauri/tauri.conf.json
src/lib/components/Modal/AutoUpdateDialog.svelte

fix: set update mode to passive in windows[]

---

src/lib/components/collections/folder-tab/MyFolder.svelte

fix refresh collection count function

fix: refresh collection count

---

src-tauri/assets/DeepLinkRegistryEntries.wxs

This PR fixes the issue of deep linking in windows if user selects a different install location.

fix: taking install directory dynamically

---

src/lib/components/collections/collection-tab/MyCollection.svelte

implemented ui for swiutch branch ..need to integrate apis

branching ui

---

src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/collections/collections-list/import-curl/ImportCurl.svelte
src/lib/components/collections/collections-list/import-curl/ImportCurl.viewModel.ts
src/lib/services/collection.service.ts

Added Curl to import request from a cURL.

feat: Added import request by curl []

---

src-tauri/src/main.rs
src/lib/api/api.common.ts
src/lib/components/collections/collection-tab/MyCollection.svelte
src/lib/components/collections/collections-list/CollectionList.ViewModel.ts
src/lib/components/collections/collections-list/collection/Collection.svelte
src/lib/components/collections/collections-list/collection/collection-utils/utils.ts
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.viewModel.ts
src/lib/components/dropdown/Dropdown.svelte
src/lib/database/app.database.ts
src/lib/models/collection.model.ts
src/lib/repositories/collection.repository.ts
src/lib/services/collection.service.ts
src/lib/utils/dto/collection.ts
src/pages/Collections/Collections.svelte

Feat: implement active sync import by URL, JSON, XML

Feat: implement active sync import by URL, JSON, XML

---

src/lib/components/Modal/InviteToWorkspace.svelte
src/lib/components/collections/req-res-section/sub-components/close-popup/ClosePopup.svelte
src/lib/components/collections/req-res-section/sub-components/request-authorization-section/NoAuth.svelte
src/lib/components/workspace/invite-to-workspace/InviteToWorkspace.svelte
src/lib/components/workspace/team-invite/TeamInvite.svelte
src/pages/Auth/entry-point/EntryPoint.svelte
src/pages/Auth/register-page/RegisterPage.svelte
src/pages/Teams/Teams.svelte

fix: minor functional and UI bugs[]

---

src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/collections/collections-list/request/Request.svelte

fix: selectedAuth not found when importing collection
double OR coming in collection import.

fix: selectedAuth not found

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte

banner for deleted apis

---

src/lib/components/collections/req-res-section/sub-components/sub-components-header/PageHeader.svelte

diabled rename api name for spec source

---

src/lib/components/editor/CodeMirrorResponse.svelte

fix: codeMirror response

---

package.json

build: Update package.json

---

src/lib/components/collections/collection-tab/MyCollection.svelte
src/lib/components/editor/CodeMirrorResponse.svelte

This PR fixes switch branch functionality for active sync collection

fix: switch branch[]

---

src-tauri/Cargo.toml
src-tauri/agpl-3.0.txt
src-tauri/tauri.conf.json

Added license to windows installer.

docs: add license

---

src/pages/Auth/login-page/login-page.ts
src/pages/Collections/Collections.svelte

Issue: https://github.com/sparrowapp-dev/sparrow-app/issues/610
closes #610

fix: login redirect collections [610]

---

src/lib/components/collections/req-res-section/sub-components/response-body-section/ResponseHeader.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/ApiSendRequestPage.svelte
src/lib/components/collections/req-res-section/sub-components/sub-components-header/CodeMirrorInput.svelte
src/lib/store/api-request.ts

Fixed the issue of edit link shortcut not working and response header UI overlapping 
#611 
#559

fix: Fixed edit link shortcut and response header UI 

---

src/lib/api/api.common.ts
src/lib/components/collections/collections-list/CollectionList.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/collections/req-res-section/RequestResponse.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.ViewModel.ts
src/lib/repositories/collection.repository.ts
src/lib/services/collection.service.ts

Please do not leave this blank ](fix: import collection external URL imports

fix: import collection external URL imports

---

src/lib/components/inputs/SelectInput.svelte

fix: text overlapping in create workspace[563]

---

src/lib/utils/deeplink/app.deeplink.ts
src/lib/utils/throttle.ts

Fix/544/653/login toast repeating/select workspace dropdown hiding

---

src/lib/utils/deeplink/app.deeplink.ts

issue #544, solved for mac os
- [ x] 👍 yes
- [x ] 🙅 no, because they aren't needed

fix: login toast repeating in mac os [544]

---

src/lib/components/collections/collections-list/collection/Collection.svelte
src/lib/components/collections/collections-list/folder/Folder.svelte
src/lib/components/collections/collections-list/request/Request.svelte
src/lib/repositories/collection.repository.ts

fix on refresh branch shift to primary branch automatically
Fixes issue #665

fix: on refresh branch shift to primary branch automatically

---

src/lib/components/collections/collections-list/empty-collection/EmptyCollection.svelte

fix: tooltip +collection viewer mistake solved [677]

---

src-tauri/agpl-3.0.txt
src-tauri/src/main.rs
src/App.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/dragdrop/DragDrop.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.svelte
src/lib/components/workspace/member-info/MemberInfo.svelte
src/lib/utils/deeplink/app.deeplink.ts
src/lib/utils/singleinstance/app.singleinstance.ts

Fixed the app crash when we open the second window of sparrow app, added single instance so only one window will open at a time.

fix: Fix app crash on second instance opening 

---

src-tauri/agpl-3.0.txt
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/dragdrop/DragDrop.svelte
src/lib/components/header/header-dashboard/HeaderDashboard.svelte
src/lib/components/workspace/member-info/MemberInfo.svelte

fixed app resize icon and issue in upload file error, and licence agreement issue #670  #683 #703 
Also fixed member permission issue and app not resizing from top #718

fix:fix app resize icon, upload file error and license agreement []

---

src/lib/components/collections/collection-tab/MyCollection.svelte
src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte
src/lib/components/collections/collections-list/request/Request.svelte
src/lib/components/inputs/index.ts
src/lib/components/inputs/select/Select.svelte
src/lib/components/inputs/select/menu-items/MenuItemsV1.svelte
src/pages/Collections/Collections.ViewModel.ts

Document Select Component  #84

feat: Document Select Component 

---

src/lib/components/collections/collections-list/import-collection/ImportCollection.svelte

setting up active sync primary branch by default while import
Fixes issue #660

fix: setting up active sync primary branch by default 

---

.github/workflows/pr-title-check.yaml
.github/workflows/pull_request_template.md

build: added issue workitem []

---

.github/workflows/feat-sparrow-refactoring.yaml

build: created new pipeline for feat/sparrow-refactoring branch []

---

src/packages/@app/pages/Environment/Environment.svelte
src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@app/pages/Teams/Teams.svelte
src/packages/@workspaces/common/components/environment-picker/EnvironmentPicker.svelte
src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte

pixel perfect design for rest explorer

feat: pixel perfect design for rest explorer

---

src/lib/repositories/tab.repository.ts
src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@common/utils/init-collection-tab.ts
src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/rest-explorer/components/request-auth/sub-auth/api-key/ApiKey.svelte
src/packages/@workspaces/features/rest-explorer/utils/decode-request.ts
src/packages/@workspaces/features/tab-bar/components/tab/Tab.svelte
src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte

Bug fixes
1. New request does not open on rightmost
2. On hovering on tab name disappears
3. Not being able to create folder

fix: functional bugs

---

src/packages/@environments/features/environment-list/components/list-item/ListItem.svelte

There was a bug in the local environment. The right click on the local environment is was not working . I added the functionality of right click.

fix: added right click functionality on local env [123]

---

src/packages/@app/styles/style.scss
src/packages/@environments/common/components/tabular-input/TabularInput.svelte

Fixed two issues :
1.There was a bug when we hover the saved environment , the hovering was not working. Fixed the effect .
2. Key value pairs and their headings were not according to figma, I did it.

fix: fixed hover funtionality in environment [123]

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte

On starting application or changing workspace, collection will be fetched from service

fix: colletion fetch issue

---

src/packages/@app/adapter/request-tab.ts
src/packages/@app/database/database.ts
src/packages/@app/models/tab.model.ts
src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@common/utils/init-request-tab.ts
src/packages/@deprecate/utils/helpers/auth.helper.ts
src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte
src/packages/@workspaces/features/rest-explorer/components/request-body/sub-body/form-data/FormData.svelte

Implementing adapter for form data making form data compatible with backend server

feat: implement adapter for form data

---

src/packages/@environments/features/environment-list/components/list-item/ListItem.svelte
src/packages/@environments/features/environment-list/layout/EnvironmentList.svelte
src/packages/@library/ui/options/Options.svelte
src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
src/packages/@workspaces/features/collection-list/components/request/Request.svelte

1.In this PR I have refactored the UI of the environment list from figma also fixes the bug of overlapping of Environment name dropdown with body of the variables
2.I also fixes a UI bug in the collection where Request type and Request is too close to each other

fix: updated ui section of environment list[123]

---

src/packages/@app/pages/Dashboard/Dashboard.svelte
src/packages/@app/pages/Help/HelpPage.svelte
src/packages/@common/components/sidebar/Sidebar.svelte
src/packages/@support/features/add-feedback/index.ts
src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
src/packages/@support/features/add-feedback/layout/index.ts
src/packages/@support/features/discord-card/index.ts
src/packages/@support/features/discord-card/layout/DiscordCard.svelte
src/packages/@support/features/discord-card/layout/index.ts
src/packages/@support/features/discord-post/index.ts
src/packages/@support/features/discord-post/layout/DiscordPost.svelte
src/packages/@support/features/discord-post/layout/index.ts
src/packages/@support/features/feedback-form/index.ts
src/packages/@support/features/feedback-form/layout/FeedbackForm.svelte
src/packages/@support/features/feedback-form/layout/index.ts
src/packages/@support/features/feedback-toast/index.ts
src/packages/@support/features/feedback-toast/layout/FeedbackToast.svelte
src/packages/@support/features/feedback-toast/layout/index.ts
src/packages/@support/features/index.ts
tsconfig.json
vite.config.ts

Feat: create feedback layout

---

src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
src/packages/@library/forms/Input/Input.svelte

fix: empty environment name bug [11]

fix: empty environment name bug [11]

---

src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte

In this PR  i have fixed the UI of the vertical tab shortcut  buttons according to Figma

fix: fix-vertical-tab-ui [123]

---

src/packages/@app/pages/Collections/CollectionsPage.svelte

fix: default workspace import [11]

---

src/packages/@support/common/constants/discord.constants.ts
src/packages/@support/features/discord-post/layout/DiscordPost.svelte
src/packages/@support/features/feedback-toast/layout/FeedbackToast.svelte

Added discord widget in sparrow app

feat: added discord widget in sparrow []

---

src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

disable active sync and fix import collection bugs

fix; disable active sync

---

src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte

In this PR i have fixes two bug that is
1.fixes header tab width according to figma
2.Added tooltip on hovering  github icon in collection sidebar

fix: Header tab UI & Added tooltip

---

src/packages/@app/pages/Help/HelpPage.svelte
src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
src/packages/@support/features/discord-card/layout/DiscordCard.svelte

fix: ui adjustments [#836]

---

src/packages/@environments/common/components/tabular-input/TabularInput.svelte
src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte

fix: disable bulk edit in tabular input [#836]

fix: disable bulk edit in tabular input [#836]

---

src/packages/@support/features/add-feedback/layout/AddFeedback.svelte

fix: refresh feedback form on successful submission

fix: refresh feedback form on successful submission [#836]

---

src/packages/@app/pages/Auth/entry-point/EntryPoint.svelte
src/packages/@workspaces/common/components/environment-picker/EnvironmentPicker.svelte

In this PR i have fixes some UI bugs from figma file
1.Launch app page ui fixed
2.Environment options ui fixed

fix: fixed login Ui &  Environment Option Ui

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
src/packages/@support/features/discord-card/layout/DiscordCard.svelte

Fix: delete collection items on api fails from collection list panel

Fix: delete collection items on api fails from collection list panel

---

src/packages/@library/ui/modal/Modal.svelte

fix: add webkit blur for multiple browser support

fix: add webkit blur for multiple browser support 

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

fix: disable tab bar red dot on api navigation

fix: disable tab bar red dot on api navigation

---

src/packages/@common/components/sidebar/SidebarItem.svelte
src/packages/@common/components/sidebar/SidebarProfileModal.svelte

fix: apply hover on sidebar profile icon

fix: apply hover on sidebar profile icon

---

src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte

fix: remove index at folder and collection explorer

fix: remove index at folder and collection explorer

---

src/packages/@app/styles/style.scss
src/packages/@library/forms/Input/Input.svelte
src/packages/@support/features/add-feedback/components/Drop/Drop.svelte
src/packages/@support/features/add-feedback/layout/AddFeedback.svelte

fix: upload multiple files in chunks - feedback form

fix: upload multiple files in chunks - feedback form

---

.github/workflows/staging.yaml

Build: CI/CD workflow created for staging branch

---

src/packages/@workspaces/common/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte

When user clicked on env found , after giving any input the popup was not vanishing .

[staging] fix : fixed the  HttpURLSection typing bug  [123]

---

src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte

In this PR the i have changed the icon for the add API Request in the collection page  and added new icon according to figma

[staging] Fix/Changed add request button icon

---

src/packages/@workspaces/features/rest-explorer/components/response-status/ResponseStatus.svelte
src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte

Reponse code of api was not aligned.

[staging] fix : reponse code is not aligned  [123]

---

src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte

In this PR i have removed the extra div element present in the code so that the code readability remains consistent

[staging] fix/Removed extra code which is not required

---

src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte

fix: rename environment items from sidebar

[staging] fix: rename environment items from sidebar

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@deprecate/utils/collections/utils.old.ts
src/packages/@workspaces/features/collection-list/components/request/Request.svelte
src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

fix: refactor import collection

[staging] fix: refactor import collection

---

src/packages/@workspaces/common/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte

[staging] fix : undo HttpURLSection typing bug  [123]

---

src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte

In this PR i have added two shortcut button for adding api and creating new folder inside a workspace  and also changed the icon for adding a api inside a folder.

[development] Feat: added api shortcut buttons

---

src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte

In this PR i have solved two bugs that is :-
1. while creating  a new collection there is two toast appearing  &
2.  On creating a new folder inside a collection there  is no toast appearing

[development] fix: Fixed multiple toast notification issue while renaming  [123]

---

src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte

When clicking on three dot icon , the menu was not toggling so added the function of it.

[development] Fix/on arrow click folder is opening

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@library/ui/dragdrop/DragDrop.svelte
src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

fix: import collection sub folder - request creation bug with undefined

[staging] fix: import collection sub folder - request creation bug with undefined

---

src/packages/@app/pages/Help/HelpPage.svelte

[development] fix : disabled right click on help page to make it consistent  [123]

---

src/packages/@workspaces/common/components/missed-environment/MissedEnvironment.svelte
src/packages/@workspaces/common/components/review-environment/ReviewEnvironment.svelte

In this PR i have fixed the hover state of copy button and add variable button in collection section

[staging] fix: fixed copy & add variable button hover state [123]

---

src/packages/@app/components/App.svelte
src/packages/@workspaces/features/tab-bar/components/tab/Tab.svelte

In this PR i have added curve in the selected tab in header tab

[staging] fix: fixed header tab ui [123]

---

src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
src/packages/@support/features/feedback-toast/layout/FeedbackToast.svelte

In this PR i have made two changes that are as follow 
1.First i change position of more and less button in the feedback section
2.I disabled the env save button when it is already saved

[staging] fix: Disabled save button & Fixed More Less button UI [123]

---

src/packages/@common/components/header/Header.svelte

fix: tooltip to position-fixed

fix: tooltip to position-fixed

---

src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte

fix: reset input on blank value

fix: reset input on blank value

---

src/packages/@workspaces/common/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte

fix: mac tooltip and codemirror issue

fix: mac tooltip and codemirror issue

---

src/packages/@app/repositories/collection.repository.ts
src/packages/@common/components/sidebar/Sidebar.svelte
src/packages/@library/ui/tooltip/Tooltip.svelte
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte

fix: z index overlap of sidebar

fix: z index overlap of sidebar

---

src/packages/@app/pages/Collections/CollectionsPage.svelte

fix: splitter border

---

src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

fix: import collection modal button width

fix: import collection modal button width

---

src/packages/@workspaces/common/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte

fix: enable environment dialog box force close

fix: enable environment dialog box force close

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts

In this PR i have changed the New collection to New Collection and also added gap between Collection name

fix: Fixed the Collection Typo and added gap in Collection name[123]

---

src/packages/@library/ui/tooltip/Tooltip.svelte
src/packages/@support/features/discord-card/layout/DiscordCard.svelte

In this PR i have changed the tooltip position and also changed z-index of tooltip

fix: Fixed tool tip position and z index [123]

---

src/packages/@workspaces/common/components/codemirror-input/CodeMirrorInput.svelte
src/packages/@workspaces/common/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte

fix: add red border on url with empty string

fix: add red border on url with empty string

---

package.json
src-tauri/tauri.conf.json

fix: update app version to 2.0.0

fix: update app version to v2.0.0

---

src/packages/@environments/features/environment-list/components/list-item/ListItem.svelte
src/packages/@support/features/discord-card/layout/DiscordCard.svelte
src/packages/@support/features/feedback-toast/layout/FeedbackToast.svelte
src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
src/packages/@workspaces/features/collection-list/components/request/Request.svelte
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte

fix : new changes [123]

---

package.json

build: made chanbges in package.json file for release lable

---

src/packages/@app/database/database.ts
src/packages/@app/models/feature-switch.model.ts
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/Dashboard/Dashboard.svelte
src/packages/@app/repositories/feature-switch.repository.ts
src/packages/@app/services/feature-switch.service.ts
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte

Added the feature switch to turn off or on any feature. #313

feat: added feature switch []

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@workspaces/features/import-collection/components/Drop/Drop.svelte
src/packages/@workspaces/features/import-collection/components/index.ts
src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

Feat: revamp import collection 
Fixes #968

Feat: revamp import collection 

---

src/packages/@app/styles/style.scss
src/packages/@workspaces/features/tab-bar/components/tab/Tab.svelte

fix : fixed the ui issue in tabs in collection tab bar  [123]

---

.github/workflows/mac-release.yml
.github/workflows/win-release.yml

Build; created separate workflow for win & mac build

---

.github/workflows/development.yaml

build: updated the workflow development.yml

---

src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
src/packages/@library/ui/carousel/Carousel.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte

fix: added some changes[123]

---

src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte

fix: Help Text Automatically Opening with Every Newly Collected Environment.[123]

---

src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte

fix: fixed bugs []

---

src/packages/@app/styles/style.scss
src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

#1057 
#1052 
In this PR i have fixed two ui bugs 
1. First is that the text in the save pop is looking like placeholder so i fixed that
2. Increased scroll bar width from 2px to 5px

fix: fixed ui bugs sprint 1 [123]

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte

FIxed save issue in import curl and over lap issue in tooltip
#1100

fix: import curl save and over lap issue []

---

.github/workflows/release.yaml
package.json

Build: Updated the label name for git release and version in workflow

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

fix: fixed toast issue[123]

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

Reverts sparrowapp-dev/sparrow-app#1129

Revert "fix: fixed toast issue[123]"

---

.env.example
src/packages/@deprecate/utils/constants.ts
src/packages/@environments/common/constants/environmentGifs.constants.ts
src/packages/@environments/common/constants/index.ts
src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
src/packages/@library/ui/carousel/Carousel.svelte
src/packages/@workspaces/common/constants/collectionGifs.constants.ts
src/packages/@workspaces/common/constants/index.ts
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
src/packages/@workspaces/features/tab-bar/layout/TabBar.svelte

#1105
added cdn based gifs in quick help

fix: added cdn based gifs []

---

src/packages/@workspaces/features/rest-explorer/components/request-doc/RequestDoc.svelte

fix: resolved comments from prev PR[123]

---

src/packages/@workspaces/features/rest-explorer/components/request-auth/RequestAuth.svelte
src/packages/@workspaces/features/rest-explorer/components/response-headers/ResponseHeaders.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte

fix: request body and height in rest explorer

fix: request body and height in rest explorer

---

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
src/packages/@app/styles/style.scss
src/packages/@deprecate/components/dashboard/rows/Rows.svelte
src/packages/@deprecate/components/dashboard/workspace-grid/WorkspaceGrid.svelte
src/packages/@deprecate/components/dashboard/workspaces/AllWorkspace.svelte
src/packages/@deprecate/components/right-click-menu/RightClickMenuView.svelte
src/packages/@deprecate/components/table/Table.svelte
src/packages/@library/ui/label/Label.svelte
src/packages/@teams/common/constants/TeamTabs.constants.ts
src/packages/@teams/features/team-explorer/components/index.ts
src/packages/@teams/features/team-explorer/components/team-navigator/TeamNavigator.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

intermediary code for team flow

feat: added grid view and list view []

---

src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

#1097 
In this PR i have added the functionality for searching the workspace

feat: Added search workspace functionality [1097]

---

src/packages/@app/pages/Teams/Teams.ViewModel.ts
src/packages/@app/pages/Teams/Teams.svelte
src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte

feat: Added Team details LHS part with navigation  [1074]

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/Dashboard/Dashboard.svelte
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@common/components/header/Header.svelte
src/packages/@library/forms/select/Select.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

This PR consist of Workspace dropdown revamp and refactoring and minor bugs #1117

feat: added workspace dropdown [1117]

---

src/packages/@app/pages/Teams/Teams.ViewModel.ts
src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte

feat: Updated Workspace page redirecting function in teams LHS section   [#1074]

---

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
src/packages/@app/repositories/workspace.repository.ts
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

Feat/workspace tab and teams 

---

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
src/packages/@teams/features/team-members/components/member/Member.svelte

enhance invite flow styling 
fixes #1106

fix: invite flow styling [#1106]

---

src/packages/@app/pages/Teams/Teams.svelte
src/packages/@teams/features/recent-apis/layout/RecentApi.svelte
src/packages/@teams/features/recent-workspace/layout/RecentWorkspace.svelte
src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte

fix: set teams lhs height to auto

fix: set teams lhs height to auto

---

src/packages/@app/database/database.ts
src/packages/@app/models/workspace.model.ts
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
src/packages/@common/components/header/Header.svelte
src/packages/@deprecate/components/header/header-dashboard/HeaderDashboard.ViewModel.ts
src/packages/@library/forms/select/Select.svelte
src/packages/@teams/common/compopnents/rows/Rows.svelte
src/packages/@teams/common/compopnents/workspace-grid/WorkspaceGrid.svelte

Fixed dropdown, updatedby, recent workspace, fetch issues

bugs from sheet

---

src/packages/@app/models/workspace.model.ts

fix: change version workspace model []

---

src/packages/@app/pages/Teams/Teams.svelte
src/packages/@library/ui/table/Table.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
src/packages/@teams/features/team-members/layout/TeamMembers.svelte

Fix: set teams rhs panel height to auto

Fix: set teams rhs panel height to auto

---

src/packages/@common/components/header/Header.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

added extra function for dropdown and style changes

fix: add dropdown callback []

---

package.json
src-tauri/tauri.conf.json

Version update for Sparrow version 2.2.0

feat: changes sparrow version []

---

src/packages/@teams/common/compopnents/rows/Rows.svelte
src/packages/@teams/common/compopnents/workspace-grid/WorkspaceGrid.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

This pull request introduces new permission controls within the team module to enhance security and streamline administrative tasks. The following changes have been implemented:
1. Invitations and Workspace Creation:
- Only team owners and admins can invite new users to the team.
- Only team owners and admins can create new workspaces within the team.
2. Team Settings Access:
- Only team owners have access to modify team settings.
3. Workspace Deletion:
- Only team owners and admins can delete workspaces.
Fixes #1088

feat: implement teams levels permissions

---

src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.svelte
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.svelte
src/packages/@app/pages/EnvironmentPage/EnvironmentPage.svelte
src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.svelte
src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.svelte
src/packages/@environments/common/components/tabular-input/TabularInput.svelte
src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte
src/packages/@environments/features/environment-list/components/list-item/ListItem.svelte
src/packages/@environments/features/environment-list/layout/EnvironmentList.svelte
src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/empty-collection/EmptyCollection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
src/packages/@workspaces/features/collection-list/components/request/Request.svelte
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte
src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
src/packages/@workspaces/features/workspace-explorer/components/workspace-about/WorkspaceAbout.svelte
src/packages/@workspaces/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
src/packages/@workspaces/features/workspace-explorer/components/workspace-navigator/WorkspaceNavigator.svelte
src/packages/@workspaces/features/workspace-explorer/layout/WorkspaceExplorer.svelte

This PR consist the checks for workspace level permissions for ADMIN, EDITOR, VIEWER
#1087

feat: workspace level permissions

---

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
src/packages/@app/pages/Teams/Teams.ViewModel.ts
src/packages/@app/pages/Teams/Teams.svelte
src/packages/@common/components/sidebar/Sidebar.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte

This PR consist of Local support for teams and workspaces
#1171

feat: added local support for teams and workspaces

---

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@teams/features/leave-team/layout/LeaveTeam.svelte

#1265 
In this PR i have refactored the function for leave team and added the loader at the leave team button

fix: Refactor leave team function & added loader in leave team button

---

src/packages/@app/styles/style.scss
src/packages/@library/forms/editor/Editor.svelte
src/packages/@library/ui/dropdown/Dropdown.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte
src/packages/@workspaces/common/components/tabular-input/sub-component/BulkEditEditor.svelte
src/packages/@workspaces/common/components/tabular-input/sub-component/bulk-edit-theme.ts
src/packages/@workspaces/features/rest-explorer/components/request-headers/RequestHeaders.svelte
src/packages/@workspaces/features/rest-explorer/components/request-parameters/RequestParameters.svelte

#1131 
#1130 
In this PR i have added  the functionality of color coding in the Bulk Edit editor .

Feat: Added bulk edit color coding

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@common/features/delete-workspace/layout/DeleteWorkspace.svelte
src/packages/@workspaces/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte

fix: bug fixes

---

src/packages/@app/pages/Teams/Teams.ViewModel.ts
src/packages/@app/pages/Teams/Teams.svelte
src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte

In this PR i have added the function which remove the New Invite text once the team is opened .

fix: Fixed New Invite visibility toggle function [123]

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@common/components/header/sub-component/PopupHint.svelte
src/packages/@library/forms/select/Select.svelte
src/packages/@teams/features/leave-team/layout/LeaveTeam.svelte
src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
src/packages/@teams/features/team-members/components/member/Member.svelte
src/packages/@teams/features/team-members/components/profile/Profile.svelte
src/packages/@workspaces/features/import-curl/layout/ImportCurl.svelte

Fixed Priority 1 bugs 
#1205 #1293 #1291 #1232 #1234 #1252

fix: fixed P1 bugs []

---

package.json
src-tauri/tauri.conf.json

This PR consist the Sparrow version update to 2.3.0.

feat: Sparrow Version change to 2.3.0 []

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

question mark not being removed from base url on query param toggle
Fixes #1227

fix: question mark not being removed from base url on query param toggle

---

package.json
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
yarn.lock

Removed svelte/srotablejs library and fixed #1316

fix: remove unwanted library and fixed create workspace bug []

---

.github/workflows/development.yaml

build: Fixed the mac build error in workflow for dev []

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
src/packages/@workspaces/features/chat-bot/components/prompt-input/PromptInput.svelte

added data pushing in chunks in local DB

feat: added data pushing in chunks in local DB for streaming like visuals []

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

added instructions for particular api request

feat: added instructions for particular api request []

---

src/packages/@workspaces/features/chat-bot/components/ai-suggestion-box/AISuggestionBox.svelte
src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte

fix: resolved comments []

---

src/packages/@workspaces/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte
src/packages/@workspaces/features/chat-bot/types/index.ts
src/packages/@workspaces/features/chat-bot/types/scroll.ts

fix: add types and jsdocs [#1243]

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

feat: added instruction for chatbot and documentation []

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
src/packages/@environments/common/components/tabular-input/TabularInput.svelte
src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte

fix: multi-instance of ai doc generartion in parallel [#1243]

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
src/packages/@workspaces/features/rest-explorer/components/request-doc/RequestDoc.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte

Restricted AI Support chatbot and generate documentation feature in sparrow edge

fix: removed AI suppport from spaarow edge []

---

src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts

This pull request ensuring that any selected environment is properly unselected upon its deletion. This prevents potential errors and enhances the user experience by maintaining a consistent state.
#1317

fix: unselect selected environment on deletion [#1317]

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@deprecate/utils/dto/ai-assistant.ts
src/packages/@environments/features/environment-list/layout/EnvironmentList.svelte
src/packages/@workspaces/common/components/codemirror-input/CodeMirrorInput.svelte
src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte

Fixed bugs and changed instructions as per requirement. 
#1286

fix: changed instructions and fixed bugs []

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@workspaces/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte
src/packages/@workspaces/features/chat-bot/components/chat-item/ChatItem.svelte
src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte

This pull request introduces a feature to implement delays in AI response generation when handling chunked data. This enhancement is aimed at improving user experience by providing a more natural and responsive interaction with the AI.
Fixes #1356

feat: implement delays to ai response generation for chunk data

---

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
src/packages/@teams/common/compopnents/rows/Rows.svelte
src/packages/@teams/common/compopnents/workspace-grid/WorkspaceGrid.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte
src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte

#1278 
In this PR i have added the option of add member in dropdown which comes when we click on three dot  on list view of workspace under Teams section.

fix: Fixed missing Add Member option in workspace list view [#1278]

---

src/packages/@app/database/database.ts
src/packages/@app/models/workspace.model.ts
src/packages/@app/pages/Auth/Auth.ViewModel.ts
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts
src/packages/@app/repositories/workspace.repository.ts
src/packages/@app/services/user.service.ts
src/packages/@teams/common/compopnents/rows/Rows.svelte

feat: addedd new tag at workspace level [#1277]

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@workspaces/features/chat-bot/layout/ChatBot.svelte

fix: chatbot instructions [#1361]

fix: chatbot instructions [#1361]

---

package.json
src-tauri/tauri.conf.json

Update Sparrow Version to 2.4.0

feat: Update Sparrow Version to 2.4.0 []

---

package.json
src-tauri/tauri.conf.json
src/packages/@common/components/header/Header.svelte

Release Version 2.4.1

---

src-tauri/Cargo.lock
src-tauri/Cargo.toml
src-tauri/src/main.rs
src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
src/packages/@deprecate/api/api.common.ts

This PR consist the RPC side of code for web  socket functionality.  #1348 
- Connect web socket function 
- Send message 
- Disconnect function

feat: added websocket RPC flow []

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@workspaces/features/import-curl/layout/ImportCurl.svelte
src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte

If this code is merged , it will handle the client-side cURL popup errors, like incorrect format , method not supported.
#1288 
also fixed the Issue number - #1359

fix: This code handles cURL popup on Client-Side[1288]

---

src-tauri/src/main.rs

Fixed panic in request builder of websocket

fix: fixed panic in websocket rpc []

---

src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts

In this  PR i have added a condition which is  triggered  when i close the environement  tab without saving the tab , so now a popup will appear for confirmation .

fix: Fixed handlepop function  on close tab for environment [#123]

---

src/packages/@workspaces/features/socket-explorer/components/response-data/ResponseData.svelte

fix: websocket bugs [#1336]

---

package.json
src-tauri/tauri.conf.json
src/packages/@app/pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts
src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte

fix: version upgrade + fix typo [#1336]

fix: version upgrade + fix typo [#1336]

---

.husky/commit-msg
.husky/pre-commit

update husky pre hook check messages
fixes #1434

fix: update husky pre hook check messages

---

.husky/pre-commit

fix: pre commit manager

---

src/packages/@support/features/update-toast/layout/UpdateToast.svelte
src/packages/@workspaces/features/socket-explorer/components/response-data/ResponseData.svelte
src/packages/@workspaces/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
src/packages/@workspaces/features/socket-explorer/components/response-preview/ResponsePreview.svelte
src/packages/@workspaces/features/socket-explorer/store/websocket.ts

Solved two issues in this PR 
#1419 
#1375

fix: solved issues in rendering [#1419]

---

src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts
src/packages/@app/pages/CollectionExplorerPage/CollectionExplorerPage.svelte
src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.svelte
src/packages/@app/repositories/tab.repository.ts
src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte

fix: collection / folder count with sync to web socket

fix: collection / folder count with sync to web socket

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/Teams/Teams.ViewModel.ts
src/packages/@app/repositories/tab.repository.ts

fix: tabs drag and drop and workspace rendering from teams module

fix: tabs drag and drop and workspace rendering from teams module

---

src/packages/@common/components/header/Header.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/layout/TeamExplorer.svelte

restrict workspace creation if already in queue

fix: restrict workspace creation if already in queue

---

src/packages/@workspaces/features/socket-explorer/components/response-data/ResponseData.svelte
src/packages/@workspaces/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte

fix: fixed the remaining websocket isssues[#1419]

---

src/packages/@app/pages/Help/HelpPage.svelte
src/packages/@library/forms/text-editor/TextEditor.svelte
src/packages/@workspaces/features/rest-explorer/components/request-doc/RequestDoc.svelte
src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte

Solved markdown bugs , please look into it.

Feat markdown/editor.js

---

src/packages/@common/components/header/Header.svelte

In this PR i have fixed the bug that is in  header team dropdown  some ui is collapsing while we increasing the ration of screen so i have fixed by increasing the minwidth of the header select component

fix: Fixed header ui collapse issue.

---

src/packages/@library/forms/editor/editor.ts

fix: fixed crash in editor []

---

package.json
src-tauri/tauri.conf.json

This version contains the version bump of sparrow 2.6.0

feat: version update to 2.6.0 []

---

src/packages/@app/services/canny.service.ts

fix: added comment for pipeling run []

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@common/components/header/Header.svelte

fix: local collection imports

---

.github/workflows/development.yaml

build: Specify the branch name in app-center build []

---

src/packages/@app/pages/Auth/entry-point/EntryPoint.svelte
src/packages/@library/ui/button/Button.svelte

feat: add automation id for testing

feat: add automation id for testing

---

src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts

http request creation from folder module

fix: http request creation from folder module

---

src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
src/packages/@common/types/workspace/testflow.ts
src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

feat: saving test flow nodes and edges to local database [#1442]

feat: saving testflow data to local database [#1442]

---

src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte

fix: fixed app crash []

---

src/packages/@app/pages/Auth/redirect/Redirect.svelte
src/packages/@library/forms/text-editor/TextEditor.svelte
src/packages/@teams/features/team-invite/layout/TeamInvite.svelte

The issue caused incorrect rendering of specific characters or sequences, leading to formatting problems. Updated the parsing logic to handle edge cases and ensure proper display of all text inputs
Fixes #1506

fix: text editor string parsing issue in the docs section [#1506]

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts

fix: handle query params for curl [#1513]

fix: handle query params for curl [#1513]

---

src/packages/@app/pages/Help/HelpPage.svelte
src/packages/@support/common/components/CommentCard.svelte
src/packages/@support/common/components/HelpInfo-Card/HelpInfoCard.svelte
src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
src/packages/@support/features/roadmap/layout/Roadmap.svelte

#1448 
In this PR I have added the Roadmap redirection functionality to particular post that belong to feedback section

feat: Added  Roadmap Page redirecting feature  [#1448]

---

src/packages/@support/common/components/CommentCard.svelte
src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
src/packages/@support/features/roadmap/layout/Roadmap.svelte

fix :fixed some general issues [#123]

---

src/packages/@app/pages/Help/HelpPage.svelte
src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
src/packages/@support/features/feedback-section/layout/FeedbackDefault.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte

Fixed category and filter bugs

fix: solve some bugs []

---

src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte

added debounce on function on search functionality

fix: added debounce on function []

---

src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
src/packages/@teams/features/team-sidepanel/layout/TeamSidePanel.svelte

Linkedin and Github Link not opening in the mac

Fix: Fixed linkedin & github link not opening issue  in mac

---

package.json
src-tauri/tauri.conf.json

feat: sparrow version bump v2.7.0 []

---

src/packages/@app/models/tab.model.ts
src/packages/@app/pages/Collections/Testflow.ViewModel.ts
src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
src/packages/@common/models/testflow.ts
src/packages/@common/utils/init-testflow-tab.ts
src/packages/@workspaces/features/socket-explorer/store/testflow.ts
src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
src/packages/@workspaces/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

feat: Run flow and select api

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
src/packages/@workspaces/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

Added environments selection in RUn flow

fix: added env in testflow run

---

src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

Feat: start block add option bug

Feat: start block add option bug

---

src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

#1400 
added notification after testflow complete

fix: added notification of testflow [#1400]

---

src/packages/@workspaces/common/components/drop-button/DropButton.svelte
src/packages/@workspaces/common/hoc/WithButtonV5.svelte
src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

fix: ui issues for testflow [#1446]

fix: ui issues for testflow [#1446]

---

src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
src/packages/@workspaces/common/components/table-navbar/TableNavbar.svelte
src/packages/@workspaces/common/components/table-sidebar/TableSidebar.svelte
src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

This pull request introduces a feature that implements a redirect rule for navigating requests within a workspace.
#1446

feat: add redirect rule for request navigation [#1446]

---

src/packages/@library/ui/carousel/Carousel.svelte

#1536
Fixed button alignment UI in the Carousel that open when we click on the help icon after creating an api reqeust then we click see how it works text.

Fix: Fixed button alignment in the carousel [#1536]

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@common/types/workspace/web-socket.ts
src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
src/packages/@workspaces/features/collection-list/components/web-socket/WebSocket.svelte

#1517
In this PR i have solved a bug , the bug is that in many places the WebSocket is written as Web Socket so i have combined that also made the S capital .

fix: Fixed WebSocket name issue [#1517]

---

src/packages/@workspaces/features/environment-list/components/list-item/ListItem.svelte
src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte

feat: testflow lists to render according to workspace switch [#1446]

feat: testflow lists to render according to workspace switch [#1446]

---

src/packages/@common/components/header/sub-component/UserProfileModal.svelte
src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
src/packages/@workspaces/features/testflow-explorer/components/index.ts
src/packages/@workspaces/features/testflow-explorer/components/run-history/RunHistory.svelte
src/packages/@workspaces/features/testflow-explorer/components/save-testflow/SaveTestflow.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

feat: add save as ui [#1533]

---

src/packages/@app/repositories/tab.repository.ts
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

Fixed issue of the syncing of data nodes with collection list on data updation

fix: sync nodes data with collection list []

---

src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

made edge non deletable related to nodes

fix: made edge non deletable []

---

src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

#1402 
In this PR i have removed on variable that is not used .

fix: resolved comments  [#1402]

---

src/packages/@app/pages/Dashboard/Dashboard.svelte
src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte

fix: replaced websocket []

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/TestflowExplorerPage/TestflowExplorerPage.svelte
src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
src/packages/@workspaces/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte

fix: connected nodes with the observable for real time data change #1400

fix: connected nodes with the observable for real time data change

---

src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte

fix: disable edge drag from nodes

fix: disable edge drag from nodes

---

src/packages/@workspaces/common/components/delete-node/DeleteNode.svelte
src/packages/@workspaces/common/components/table-navbar/TableNavbar.svelte
src/packages/@workspaces/features/testflow-explorer/layout/TestflowExplorer.svelte
src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte

#1402
In this PR i have solved some bug in test flow

Fix: Fixed some bug in testflows

---

src/packages/@workspaces/features/testflow-explorer/components/request-block/RequestBlock.svelte
src/packages/@workspaces/features/testflow-explorer/components/start-block/StartBlock.svelte

feat: add drag at start block [#1398]

feat: add drag at start block [#1398]

---

src/packages/@workspaces/features/testflow-explorer/components/run-history/RunHistory.svelte
src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte

[#123]
Changed name  for adding the Rest api request in default page .

fix: fixed name in default page [#123]

---

src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte

fix: fixed undefined issue in activity section [#123]

fix: fixed undefined issue in activity section [#123]

---

src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
src/packages/@support/features/roadmap/layout/Roadmap.svelte

#12345
In this PR i have solved two minor bugs one is category filter and another one is url not found in release notes.

fix: Fixed some general issue 

---

package.json
src-tauri/tauri.conf.json

This PR is raised to Upgrade Sparrow to v2.8.0

feat: Upgraded Sparrow to V2.8.0 []

---

package.json

fix: add run scripts to package json

---

apps/@sparrow-web/vite.config.ts

fix: web imports

---

apps/@sparrow-desktop/package.json
apps/@sparrow-web/package.json
apps/@sparrow-web/src/App.svelte
package.json
packages/@sparrow-common/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-workspaces/package.json

add web app packages dependencies to the app #1669

Feat: add web app packages dependencies to the app

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts
src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte
src/packages/@deprecate/api/api.common.ts
src/packages/@workspaces/common/components/drop-button/DropButton.svelte
src/packages/@workspaces/common/type/actions.ts
src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte
src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
src/packages/@workspaces/features/rest-explorer/store/index.ts
src/packages/@workspaces/features/rest-explorer/store/rest-explorer.ts

fix: add abort controller to hash map to handle multiple tabs

fix: add abort controller to hash map to handle multiple tabs

---

src/packages/@deprecate/api/api.common.ts

fix: handle null signal rejection for http client

fix: handle null signal rejection for http client

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@app/services/collection.service.ts
src/packages/@app/styles/style.scss
src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte

This PR includes postman collection support  import for v2.1.
#1662

feat: added postman collection support [#1662]

---

src/packages/@workspaces/features/collection-list/components/empty-collection/EmptyCollection.svelte

fix: fixed ui bugs [#1697]

---

src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
src/packages/@app/repositories/environment.repository.ts
src/packages/@workspaces/features/workspace-actions/layout/WorkspaceActions.svelte

Fixed [Left side panel] UI bugs of Left side panel
- Design was not up to date with figma which is now fixed
- Add Collection Feature was not present in workspace Add List which is now fixed

[Left side panel] UI bugs of Left side panel

---

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts

fix: default response state in rest api tool

fix: default response state in rest api tool

---

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts
src/packages/@app/pages/Collections/Testflow.ViewModel.ts
src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/Dashboard/Dashboard.svelte
src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts
src/packages/@app/repositories/collection.repository.ts
src/packages/@app/repositories/environment.repository.ts
src/packages/@app/repositories/testflow.repository.ts
src/packages/@deprecate/api/api.common.ts

fix: perform rxdocument delete operation for env, testflow and colletions [#1682]

fix: perform rxdocument delete operation for env, testflow and colletions

---

src/packages/@library/forms/multi-select/MultiSelect.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte

Fix:Fixed workspace page UI issue [#1614]

Fix:Fixed workspace page UI issue [#1614]

---

src/packages/@app/pages/Auth/entry-point/EntryPoint.svelte
src/packages/@app/pages/Collections/CollectionsPage.svelte

fix: fixed multiple create tab in edge []

---

src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte

fix: fixed workspace list view pagination ui [#1614]

fix: fixed workspace list view pagination ui [#1614]

---

src/packages/@app/pages/Auth/login-page/login-page.ts

added signup and login events with method

feat: added signup and login events with method []

---

src/packages/@app/pages/Dashboard/Dashboard.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte
src/packages/@app/pages/Teams/Teams.ViewModel.ts
src/packages/@app/pages/Teams/Teams.svelte
src/packages/@app/repositories/team.repository.ts
src/packages/@deprecate/api/api.common.ts
src/packages/@deprecate/utils/enums/enums.ts

fix: perform teams rxdocument deletion

fix: perform teams rxdocument deletion

---

src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/environment-list/layout/EnvironmentList.svelte
src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte
src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte

Update message on search query for left panel

---

src/packages/@app/pages/Help/HelpPage.ViewModel.ts
src/packages/@app/pages/Help/HelpPage.svelte
src/packages/@app/services/canny.service.ts
src/packages/@support/common/components/CommentCard.svelte
src/packages/@support/features/activity-section/layout/ActivitySection.svelte
src/packages/@support/features/add-feedback/layout/AddFeedback.svelte
src/packages/@support/features/feedback-section/layout/FeedbackPost.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
src/packages/@support/features/roadmap/layout/Roadmap.svelte

fix: fixed  some ui issues mentioned in the loop doc [#1686]

fix: fixed  some ui issues mentioned in the loop doc [#1686]

---

src/packages/@teams/features/create-workspace/components/workspace-actions/WorkspaceActions.svelte
src/packages/@teams/features/create-workspace/components/workspace-name/WorkspaceName.svelte

fix: trim workspace name for creation

fix: trim workspace name for creation

---

src/packages/@support/features/activity-section/layout/ActivitySection.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
src/packages/@support/features/roadmap/layout/Roadmap.svelte

fix: fixed cross icon in search bar [#1686]

fix: fixed cross icon in search bar [#1686]

---

src-tauri/tauri.conf.json

fix: remove uninstaller script for windows

fix: remove uninstaller script for windows

---

src/packages/@app/pages/Help/HelpPage.ViewModel.ts
src/packages/@app/services/canny.service.ts
src/packages/@deprecate/components/collections/collection-tab/MyCollection.svelte
src/packages/@deprecate/components/collections/collections-list/CollectionList.old.svelte
src/packages/@support/features/activity-section/layout/ActivitySection.svelte
src/packages/@support/features/feedback-section/layout/FeedbackSection.svelte
src/packages/@support/features/release-notes/layout/ReleaseNotes.svelte
src/packages/@support/features/roadmap/layout/Roadmap.svelte
src/packages/@teams/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
src/packages/@teams/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
src/packages/@teams/features/team-members/layout/TeamMembers.svelte
src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/socket-explorer/components/http-url-section/HttpUrlSection.svelte
src/packages/@workspaces/features/socket-explorer/components/response-data/ResponseData.svelte
src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte
src/packages/@workspaces/features/workspace-default/layout/WorkspaceDefault.svelte

fix: Fixed loop doc ui bugs [#1234]

fix: Fixed loop doc ui bugs [#1234]

---

src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
src/packages/@workspaces/features/collection-list/components/request/Request.svelte
src/packages/@workspaces/features/environment-list/components/list-item/ListItem.svelte
src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte

#1703 
Fix: Fixed left panel text UI and naming convetion .

Fix: Fixed left panel text UI and naming convention.

---

src/packages/@workspaces/features/collection-list/layout/CollectionList.svelte
src/packages/@workspaces/features/rest-explorer/components/request-auth/sub-auth/basic-auth/BasicAuth.svelte
src/packages/@workspaces/features/testflow-list/layout/TestflowList.svelte

fix: empty search text

---

src/packages/@support/features/add-feedback/layout/AddFeedback.svelte

fix: Fixed add feedback issue [#1724]

fix: Fixed add feedback issue [#1724]

---

src/packages/@app/pages/Collections/CollectionsPage.svelte
src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte

fix: undefined on collection deletion

fix: undefined on collection deletion

---

src/packages/@workspaces/features/rest-explorer/components/response-default-screen/ResponseDefaultScreen.svelte

fix: revert show scroll bar on hover from api response page

---

package.json
src-tauri/tauri.conf.json

feat: updated sparrow version to v2.9.0 []

---

src/packages/@workspaces/features/environment-list/components/list-item/ListItem.svelte
src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte

env and tesflow popup position

fix: env and tesflow popup position []

---

src/packages/@workspaces/features/collection-list/components/collection/Collection.svelte
src/packages/@workspaces/features/collection-list/components/request/Request.svelte
src/packages/@workspaces/features/environment-list/components/list-item/ListItem.svelte
src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
src/packages/@workspaces/features/socket-explorer/components/socket-navigator/SocketNavigator.svelte
src/packages/@workspaces/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte

In this PR I have solved two  UI bugs that is realted to UI

fix: Fixed some ui issues [#1234]

---

package.json
packages/@sparrow-support/src/features/activity-section/layout/ActivitySection.svelte

fix: fixed import of upvote

---

.github/workflows/development.yaml

made changes in development workflow []

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
apps/@sparrow-web/src/containers/api/api.common.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/Teams/Teams.svelte
packages/@sparrow-teams/package.json
packages/@sparrow-teams/src/features/index.ts
packages/@sparrow-teams/src/features/list-team-navigation/components/index.ts
packages/@sparrow-teams/src/features/list-team-navigation/components/team-heading/TeamHeading.svelte
packages/@sparrow-teams/src/features/list-team-navigation/components/team-naigation/TeamNavigation.svelte
packages/@sparrow-teams/src/features/list-team-navigation/index.ts
packages/@sparrow-teams/src/features/list-team-navigation/layout/ListTeamNavigation.svelte
packages/@sparrow-teams/src/features/team-list/index.ts
packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte

feat: integrate web teams with compatibility to desktop

feat: integrate web teams with compatibility to desktop

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

fix: fixed a logic issue in opening select dropdown [#1644]

fix: fixed a logic issue in  opening select dropdown [#1644]

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

Reverts sparrowapp-dev/sparrow-app#1824

Revert "fix: fixed a logic issue in  opening select dropdown [#1644]"

---

packages/@sparrow-common/src/components/index.ts
packages/@sparrow-common/src/components/pulse-circle/PulseCircle.svelte
packages/@sparrow-library/src/ui/dropdown/Dropdown.svelte
packages/@sparrow-workspaces/src/components/index.ts
packages/@sparrow-workspaces/src/components/table-navbar/TableNavbar.svelte
packages/@sparrow-workspaces/src/components/test-flow-tour-guide/TestFlowTourGuide.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/start-block/StartBlock.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
packages/@sparrow-workspaces/src/stores/guide.tour.ts
packages/@sparrow-workspaces/src/stores/index.ts

Reverts sparrowapp-dev/sparrow-app#1827

Revert "Revert "Feat: Added tour guide test flow [#1641]""

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

Reverts sparrowapp-dev/sparrow-app#1825

Revert "Revert "fix: fixed a logic issue in  opening select dropdown [#1644]""

---

packages/@sparrow-workspaces/src/components/table-navbar/TableNavbar.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

Fix:  Added test flow tour guide [#1641]

Fix:  Added test flow tour guide [#1641]

---

apps/@sparrow-web/src/components/App.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts

feat: handle redirect for web app, when enter web app without access token will get redirected to the identity app.

feat: handle redirect for web app

---

packages/@sparrow-common/src/components/pulse-circle/PulseCircle.svelte

fix: Added Pulse effect in tour guide  [#1644 ]

fix: Added Pulse effect in tour guide

---

packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

Added the missing open in desktop button and its functionality in grid view in teamexplorerpage of webapp.

fix: open in desktop added in grid view too

---

packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-common/src/features/create-team/components/team-icon/TeamIcon.svelte
packages/@sparrow-common/src/utils/OSDetector.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte

fix: fixed some bugs in creating a team in web app  #1552 
This PR fixes bugs that is realted to a function that i used to check the os of the place where app is runnig so previously we are using platform package of tauri which is giving error in web app so here we have used js technique to check the os .
Also fix one enhancement that is new team name is appearing in bottom but is should appear to top.

fix: fixed some bugs in creating a new team

---

apps/@sparrow-web/deploymentManifests/deployment.yml

 Added livenessProbe & readinessProbe in sparrow-web []

---

apps/@sparrow-web/deploymentManifests/deployment.yml

 fix mapping issue in deployment file[]

---

apps/@sparrow-desktop/src/pages/auth-page/sub-pages/login-page/login-page.ts
apps/@sparrow-desktop/src/pages/workspace-page/Testflow.ViewModel.ts
packages/@sparrow-workspaces/src/components/test-flow-tour-guide/TestFlowTourGuide.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/stores/guide.tour.ts
packages/@sparrow-workspaces/src/stores/index.ts

fix: fixed issues in tour guide [#1848]

fix: fixed issues in tour guide [#1848]

---

packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte

Fix: Fixed issue in sample api #1848

Fix: Fixed issue in sample api

---

packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte

fix: fixed issue in first time tour guide start   [#1848 ]

fix: fixed issue in first time tour guide start

---

packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte

fix: fixed ui  issue in left panel   #1840

fix: Fixed ui issues  

---

apps/@sparrow-web/deploymentManifests/deployment.yml

 Added strategy type in deployment.yml for sparrow-web[]

---

apps/@sparrow-web/deploymentManifests/deployment.yml

Reverts sparrowapp-dev/sparrow-app#1895

Revert " Added strategy type in deployment.yml for sparrow-web[]"

---

apps/@sparrow-desktop/src/components/app.ViewModel.ts
apps/@sparrow-desktop/src/utils/jwt.ts

fix: add throttler to deeplink redirect rule

---

apps/@sparrow-web/src/pages/Teams/Teams.svelte
packages/@sparrow-teams/src/compopnents/menu-view/MenuView.svelte
packages/@sparrow-teams/src/compopnents/rows/Rows.svelte
packages/@sparrow-teams/src/compopnents/workspace-grid/WorkspaceGrid.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte

fix: teams and workspaces UI

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
package.json

 Version bump 2.10.0 []

---

packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte

fix: environment render conditions

fix: environment render conditions

---

apps/@sparrow-desktop/src/adapter/socket-io-tab.ts
apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/SocketIoExplorerPage/SocketIoExplorerPage.ts
apps/@sparrow-desktop/src/services/collection.service.ts
packages/@sparrow-common/src/utils/init-socket-io-tab.ts
packages/@sparrow-workspaces/src/features/save-as-request/components/file-type/FileType.svelte
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte

feat: implement socket io template

feat: implement socket io template

---

apps/@sparrow-desktop/src/styles/style.scss
packages/@sparrow-common/src/features/delete-workspace/layout/DeleteWorkspace.svelte
packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte
packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body/ResponseBody.svelte
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

This PR addresses various regression issues that have arisen in the workspace functionality. Following recent changes, several components were found to be misbehaving, leading to degraded performance and user experience. The following key areas have been resolved:
- Component Stability: Restored stability to the affected components that were crashing or displaying incorrect information due to recent updates.
- Performance Improvements: Optimized the performance of workspace-related functions, reducing load times and enhancing responsiveness.
Fix #1728

fix: workspace regression issues

---

packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte

fix: Replace web socket icon with socket io

fix: Replace web socket icon with socket io

---

apps/@sparrow-desktop/src/styles/style.scss
packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte

feat: Udpated  the UI part for  socket-io header [#1893]

feat: Udpated  the UI part for  socket-io header [#1893]

---

packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte

Fix: Sync tabular input with form data in desktop.

Fix: Sync tabular input with form data in desktop.

---

packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte

Fix: UI for tabular input

---

.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
apps/@sparrow-desktop/src-tauri/Cargo.lock
apps/@sparrow-desktop/src-tauri/Cargo.toml
apps/@sparrow-desktop/src-tauri/src/main.rs
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts

feat: added socket io function in RPC #1884

---

apps/@sparrow-desktop/src/adapter/socket-io-tab.ts
packages/@sparrow-common/src/utils/init-socket-io-tab.ts

fix: added Event Saving function of event data in backend database [#1890]

fix: added Event Saving function of event data in backend database [#1890]

---

packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte

fix: Added socket io Filter Ffunctionality [#1881]

fix: Added socket io Filter Functionality [#1881]

---

apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts
apps/@sparrow-web/src/pages/Teams/Teams.svelte
apps/@sparrow-web/src/repositories/team.repository.ts
apps/@sparrow-web/src/repositories/workspace.repository.ts

fix: workspace and teams deletion on web app
#1926

fix: workspace and teams deletion on web app

---

apps/@sparrow-desktop/src-tauri/src/main.rs
packages/@sparrow-common/src/enums/mixpanel-events.enum.ts
packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/sub-body/request-body-navigator/RequestMessageNavigator.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

#1912 
Fixed namespace error in Rust

feat: added mixpanel events and fixed namespace error issue in rust []

---

.github/workflows/development.yaml

This PR is for testing the intel-based mac build

build: update development build yaml

---

packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte

download and copy button on web socket
#1963

fix: download and copy button on web socket

---

apps/@sparrow-desktop/package.json
package.json

fix: package version upgrade

---

.github/workflows/development.yaml

This PR is to test mac-intel build creation.

build: update development yaml to support intel based mac build

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/gen/schemas/windows-schema.json
package.json
yarn.lock

In these PR tauri-apps/cli package version is upgraded to rc version.

feat: updated tauri-apps/cli version []

---

apps/@sparrow-desktop/src/pages/help-page/HelpPage.ViewModel.ts
packages/@sparrow-library/src/ui/image-modal/ImageModal.svelte
packages/@sparrow-support/src/features/add-feedback/layout/AddFeedback.svelte
packages/@sparrow-support/src/features/feedback-section/layout/FeedbackPost.svelte
packages/@sparrow-support/src/features/feedback-section/layout/FeedbackSection.svelte
packages/@sparrow-support/src/features/roadmap/layout/Roadmap.svelte

Fixed issue in help moudle mentioned in this ticket [#1851 ]

Fix: Fixed help module issues [#1851]

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-web/src/containers/api/api.common.ts
packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/response-data/ResponseData.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/store/websocket.ts
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte

fix: Fixed Regression issues [#1801]
Fixed:
1. Removed tooltip on the collection name appeared when we are a viewer
2. Fixed websocket and socket io response filter state bug .

fix: Fixed Regression issues [#1801]

---

packages/@sparrow-teams/src/features/workspace-members/layout/WorkspaceMembers.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte

fix: fixed no result found message missing on searching member [#253]

fix: fixed no result found message missing on searching member [#253]

---

apps/@sparrow-desktop/src-tauri/src/main.rs
apps/@sparrow-desktop/src/containers/api/api.common.ts
packages/@sparrow-common/src/types/workspace/socket-io-request-tab.ts

Fixed below issues with the code, 
1) Invalid namespace handle
2) Multiple listeners issue

fix: socket io fixes

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/gen/schemas/windows-schema.json
package.json
yarn.lock

Reverts sparrowapp-dev/sparrow-app#2011

Revert "feat: updated tauri-apps/cli version []"

---

apps/@sparrow-desktop/src-tauri/src/main.rs
apps/@sparrow-desktop/src/containers/api/api.common.ts

Added send graphql function in RPC #1987

feat: added send graphql function in RPC []

---

apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-desktop/src/routing/NavRoute.svelte

feat: added signature key in tauri config []

---

apps/@sparrow-desktop/src-tauri/src/main.rs

Socket was getting auto-disconnected when the user quickly disconnected and reconnected the socket multiple times in a row.

fix: socket auto disconnection

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte

fix: fixed ui of graplql Header [#1994]

fix: fixed ui of header [#1994]

---

.github/workflows/development.yaml
package.json

feat: universal builder

---

packages/@sparrow-workspaces/src/components/index.ts
packages/@sparrow-workspaces/src/components/navigator/Navigator.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-navigator/RequestNavigator.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-navigator/RequestNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-status/ResponseStatus.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/socket-navigator/SocketNavigator.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-navigator/RequestNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/request-navigator/RequestNavigatorTestFlow.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

fix: fixed navigator ui all over the request and response [#1800 ]
This PR fixes the issue ithe inconsistency in the UI of navigator for request and response so created a dynamic component which will used for all the req and response thing .

fix: fixed navigator ui all over the request and response

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-navigator/ResponseNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/socket-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/hoc/WithButtonV6.svelte
packages/@sparrow-workspaces/src/hoc/index.ts

feat: added hoc for copy and download requests [#1985]

feat: added hoc for copy and download requests [#1985]

---

.github/workflows/development.yaml

fix: revert changes

---

apps/@sparrow-desktop/src/containers/api/api.common.ts
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-data/ResponseData.svelte

fix: message event listener for socket io

fix: message event listener for socket io

---

packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-invite/layout/TeamInvite.svelte
packages/@sparrow-teams/src/features/team-members/layout/TeamMembers.svelte
packages/@sparrow-teams/src/features/team-settings/components/team-profile/sub-team-profile/icon-uploader/IconUploader.svelte
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/WorkspaceSetting.svelte
packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-settings/sub-workspace-settings/member/Member.svelte

fix: fixed bugs [#2044] [#2045] [#2047] [#2040]

fix: fixed bugs mentioned in  [#2044] [#2045] [#2047] [#2040]

---

packages/@sparrow-common/src/enums/mixpanel-events.enum.ts
packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

Added mix panel events for graphql [#1996]

Feat: Added mix panel events for graphql [#1996]

---

packages/@sparrow-teams/src/features/recent-apis/layout/RecentApi.svelte

Fixed the recent api issue in left panel [#2042 ]

fix: fixed recent api , add restriction to five api only [#2042]

---

apps/@sparrow-desktop/src/containers/api/api.common.ts

feat: added logger for graphql RPC time metric []

---

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
packages/@sparrow-teams/src/features/team-explorer/components/workspace-list-view/WorkspaceListView.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-teams/src/features/team-members/components/profile/sub-profile/profile-workspace/ProfileWorkspace.svelte

fix: update workspace access permission to team member [#1961]

fix: update workspace access permission to team member [#1961]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

fix: save graphql request bugs [#1993]

fix: save graphql request bugs [#1993]

---

apps/@sparrow-desktop/src-tauri/src/main.rs
apps/@sparrow-desktop/src/containers/api/api.common.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts

Added auto disconnection in web socket in case of server down

feat: added websocket auto-disconnection []

---

packages/@sparrow-workspaces/src/components/codemirror-input/sub-input/code-mirror-handler/CodeMirrorHandler.svelte

fix: codemirror input code handler
#2032

fix: codemirror input code handler

---

packages/@sparrow-library/src/forms/select/menu-items/MenuItemsV3.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte
packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte
packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte

[#2044] [#2042]
fix: Fixed Ellipsis missing on searching workspaces.

fix: Fixed Ellipsis missing on searching workspaces.

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Upgraded sparrow version to 2.12.0

feat: upgrade sparrow to version 2.12.0 []

---

.github/workflows/release.yaml

updated release.yml file[]

---

packages/@sparrow-teams/src/features/list-team-navigation/components/team-heading/TeamHeading.svelte
packages/@sparrow-teams/src/features/recent-workspace/layout/RecentWorkspace.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

fix: teams and collaboration ui bugs

fix: teams and collaboration ui bugs

---

packages/@sparrow-common/src/components/sidebar/Sidebar.svelte
packages/@sparrow-library/src/forms/select/menu-items/MenuItemsV3.svelte
packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte

fix: fixed bugs from loop doc of sep 16 to sep 20

fix: fixed bugs from loop doc of sep 16 to sep 20

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts

Added function to transform the schema as per required json
#2077

feat: added transform schema function []

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts

feat: create query form JSON

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/generate-query/GenerateQuery.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/response-status/ResponseStatus.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
packages/@sparrow-workspaces/src/hoc/WithSelect.svelte

fix: add search behaviour with lowercase [#2079]

fix: add search behaviour with lowercase [#2079]

---

apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte
packages/@sparrow-common/src/components/header/Header.svelte

fix: disabled custom header for now []

---

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte

This is testing  PR for the blocker that was arising in the mac for custom header , this can be reverted if the functionality will still break on mac .

fix : header bugs in mac

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts

Fixed  indentation issue in generated query and added limit of 100 in query and mutation item with limit of 20 in nested items.

fix: indentation in query and long schema []

---

apps/@sparrow-web/src/containers/api/api.common.ts

Fixed body and content type issues in browser agent

fix: fixed browser Agent Body issues []

---

packages/@sparrow-library/src/ui/image-modal/ImageModal.svelte
packages/@sparrow-library/src/ui/modal/Modal.svelte

fix: fixed the tab button by disabling it when the modal is open

fix: fixed the tab button by disabling it when the modal is open

---

packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte

fix : delete icon size in body form data

---

apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/RequestBody.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/request-body/sub-body/form-data/FormData.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte

fix: disabled swagger link import and download in Web app []

---

packages/@sparrow-library/src/forms/editor/Editor.svelte

fix: unnecessary re-renders of code mirror

fix: unnecessary re-renders of code mirror

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts

Integrated the schema change function on change of query. It will update the schema as something changes in query.

feat: added reverse query to schema feature []

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
packages/@sparrow-common/src/types/workspace/graphql-request-base.ts

fix: graphql save in folder bug [#2083]

fix: graphql save in folder bug [#2083]

---

apps/@sparrow-desktop/index.html
apps/@sparrow-desktop/src/components/App.svelte
apps/@sparrow-desktop/src/pages/auth-page/sub-pages/login-page/login-page.ts
apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.svelte
apps/@sparrow-desktop/src/utils/index.ts
apps/@sparrow-desktop/src/utils/window-resize.ts
apps/@sparrow-desktop/src/utils/zoom.ts

Set max and min zoom.
Window will maximize on startup.

fix: zoom and resize window on start

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

Upgraded sparrow version to 2.13.0

feat: upgraded sparrow to v2.13.0 []

---

.github/workflows/development.yaml
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-desktop/src/components/App.svelte

fix: empty branch name[]

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/Cargo.toml
apps/@sparrow-desktop/src-tauri/tauri.conf.json
package.json
yarn.lock

Revert tauri cli to beta version to fix build break on both windows and mac.

feat: revert tauri  cli package to beta[]

---

packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

I have updated the position of caution in save pop-up.

bug:resolved-overlapping[#2168]

---

apps/@sparrow-desktop/src/pages/auth-page/Auth.svelte

FIx: Fixed Color issue in init page button

FIx: Fixed Color issue in init page button

---

apps/@sparrow-desktop/src-tauri/Cargo.lock
apps/@sparrow-desktop/src-tauri/Cargo.toml
apps/@sparrow-desktop/src-tauri/src/main.rs
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-desktop/src/components/App.svelte
packages/@sparrow-common/src/components/default-header/DefaultHeader.svelte
packages/@sparrow-common/src/components/header/window-action/WindowAction.svelte

This PR fixes the rounded corner issue in tauri window in MacOS.

fix: mac rounded corners

---

.github/workflows/sparrow-web-dev.yml

build: fix docker build issue []

---

apps/@sparrow-desktop/src-tauri/capabilities/migrated.json

feat: added windows as a valid webview[]

---

.github/workflows/development.yaml
.github/workflows/release.yaml

build: Added CI: false ENV in dev & prod workflow []

---

apps/@sparrow-web/src/containers/api/api.common.ts

fix : browser agent bug

---

apps/@sparrow-web/src/pages/Teams/Teams.svelte
packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte

fix : crate team modal bug fixed

---

apps/@sparrow-web/src/containers/api/api.common.ts
packages/@sparrow-common/src/components/header/Header.svelte

fix: disabled proxy agent in ws send message []

---

apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/features/save-as-request/layout/SaveAsRequest.svelte

fix: save socket io and ws from top tab []

---

apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/TeamExplorerPage/TeamExplorerPage.svelte
packages/@sparrow-teams/src/features/team-explorer/components/team-navigator/TeamNavigator.svelte
packages/@sparrow-teams/src/features/team-explorer/layout/TeamExplorer.svelte

feat: added team members and settings tab []

---

packages/@sparrow-workspaces/src/features/graphql-explorer/components/http-url-section/HttpUrlSection.svelte
packages/@sparrow-workspaces/src/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte

I have applied condition to check before sending the Toast-message[#2234].

fix: resolved multiple toast message appearing/[#2234]

---

packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte

I have corrected the message placeholder according to the Figma design[#2217].

Fix: resolved collection placeholder message[#2217]

---

apps/@sparrow-web/src/components/App.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
apps/@sparrow-web/src/pages/Dashboard/Dashboard.svelte

feat: added support of edge in web app [#2289]

---

apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/repositories/testflow.repository.ts
packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
packages/@sparrow-workspaces/src/features/tab-bar/components/tab/Tab.svelte
packages/@sparrow-workspaces/src/features/tab-bar/layout/TabBar.svelte
packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte
packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
packages/@sparrow-workspaces/src/features/workspace-default/layout/WorkspaceDefault.svelte

This pull request introduces the API Test Flow Management feature, enabling streamlined testing workflows for APIs.
#2296

feat: Introduced the API Test Flow Management feature, enabling streamlined testing workflows for APIs.

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
apps/@sparrow-web/src/containers/api/api.common.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.ViewModel.ts
packages/@sparrow-workspaces/src/features/testflow-explorer/components/select-api/SelectAPIRequest.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

feat: integrate user agent to testflow [#2298]

feat: integrate user agent to web app testflow [#2298]

---

packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte

[#2354](https://github.com/sparrowapp-dev/sparrow-app/issues/2354)
- [ .] 🐛 Bug Fix
- [. ] 👍 yes
- [.] 🙋 no, because I need help

changed DELETE to DEL in req section

---

packages/@sparrow-common/src/components/header/Header.svelte

Please do not leave this blank.
I have updated the size of the agent dropdown in the web app according to the Figma design[#2338].

fix: updated webapp agent dropdown size[#2338]

---

packages/@sparrow-workspaces/src/features/invite-to-workspace/layout/InviteToWorkspace.svelte

I have updated the validation message accordingly[#2360]

fix: validation message in invite workspace popup

---

packages/@sparrow-common/src/features/create-team/components/icon-uploader/IconUploader.svelte

I have increased the size of the icons according to the figma[#2342].

fix : Teams edit ,delete icons size issue[#2342]

---

apps/@sparrow-desktop/src/pages/teams-page/Teams.svelte
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte

I have resolved the issue with redirecting on click of the GitHub icon. [#2274].

fix: resolved github star navigation in workspace.

---

apps/@sparrow-desktop/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte
apps/@sparrow-web/src/pages/workspace-page/CollectionPage.ViewModel.ts
apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte
packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte

#2306 
Added support of deployed swagger and localhost swagger in import collection. 
Fixed collection list not opening bug

feat: added support for Swagger and localhost support in collection import [#2306]

---

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
apps/@sparrow-web/src/containers/api/api.common.ts
apps/@sparrow-web/src/pages/workspace-page/sub-pages/TestflowExplorerPage/TestflowExplorerPage.svelte
packages/@sparrow-common/src/utils/base64Converter.ts
packages/@sparrow-common/src/utils/index.ts
packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte

- Added functionality to handle HTTP request form data in the web app.
- Implemented support for form data serialization and submission.
- Ensured compatibility with existing HTTP request workflows.
- Added validation and error handling for form data fields.
- Updated relevant components and documentation to reflect changes.
#2307

feat: Implement HTTP request form data handling in web app

---

apps/@sparrow-desktop/src/pages/auth-page/sub-pages/login-page/login-page.ts
apps/@sparrow-desktop/src/utils/singleinstance/app.singleinstance.ts

fix: disabled maximize and minimize on login []

---

apps/@sparrow-web/src/components/App.ts
packages/@sparrow-common/src/components/banner/login-banner.svelte
packages/@sparrow-workspaces/src/features/import-collection/layout/ImportCollection.svelte

fix: fixed create account btn z-index [#2381]

---

packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte

fix: reupload form data files

---

apps/@sparrow-web/index.html
packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-common/src/components/header/sub-component/PopupHint.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/components/response-preview-navigator/ResponsePreviewNavigator.svelte
packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte

fix: guest user regression issue

fix: guest user regression issue

---

packages/@sparrow-common/src/components/header/Header.svelte

fix: fixed padding issue in login btn edge []

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src-tauri/tauri.conf.json
apps/@sparrow-web/package.json
package.json
packages/@sparrow-common/package.json
packages/@sparrow-library/package.json
packages/@sparrow-support/package.json
packages/@sparrow-teams/package.json
packages/@sparrow-types/package.json
packages/@sparrow-workspaces/package.json

feat: upgrade app version

---

package.json
packages/@sparrow-storybook/package.json
packages/@sparrow-storybook/src/stories/Button.stories.js

feat: add storybook build server

feat: add storybook build server

---

apps/@sparrow-desktop/package.json
apps/@sparrow-desktop/src/adapter/graphql-tab.ts
apps/@sparrow-desktop/src/database/database.ts
apps/@sparrow-desktop/src/models/tab.model.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.ViewModel.ts
apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/GraphqlExplorerPage/GraphqlExplorerPage.svelte
apps/@sparrow-desktop/src/services/collection.service.ts
package.json
packages/@sparrow-common/src/components/default-header/DefaultHeader.svelte
packages/@sparrow-common/src/components/header/Header.svelte
packages/@sparrow-common/src/types/workspace/graphql-request-dto.ts
packages/@sparrow-common/src/types/workspace/graphql-request-tab.ts
packages/@sparrow-common/src/utils/init-graphql-tab.ts
packages/@sparrow-library/src/forms/editor/Editor.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/components/request-query/RequestQuery.svelte
packages/@sparrow-workspaces/src/features/graphql-explorer/layout/GraphqlExplorer.svelte
yarn.lock

fix: added mutation tab in graphql and fixed known bugs [#2419]

---

apps/@sparrow-storybook/src/stories/Shadow/Shadow.docs.mdx

Storybook - Shadows
[#2413](https://github.com/sparrowapp-dev/sparrow-app/issues/2413)

Storybook - Shadows #2413

---

apps/@sparrow-storybook/src/stories/Spacing/Spacing.docs.mdx

Storybook - Spacing
[#2412](https://github.com/sparrowapp-dev/sparrow-app/issues/2412)

Storybook - Spacing #2412
