sparrowapp-dev/sparrow-app

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/assets/DeepLinkRegistryEntries.wxs, src-tauri/src/main.rs, src-tauri/tauri.conf.json
App crashing on windows after trying to set registry keys automatically on app start. This was happening due to app being run without admin privileges. 
Fix - Setting registry keys on installer level.
=> fix: windows deep link[]

src/lib/components/dashboard/rows/Rows.svelte, src/lib/components/dashboard/workspace-grid/WorkspaceGrid.svelte, src/lib/components/workspace/workspace-tab/myWorkspace.svelte, src/lib/components/workspace/workspaceSetting.svelte
Deprecate right click option on team workspaces
=> fix: deprecate right click option on team workspaces 

src/lib/components/inputs/SelectInput.svelte
closes #563 
Last time, in create workspace, team icon was overlapped by text, this is fixed.
=> fix: team icon overlapped by text [610]

src/lib/components/collections/collections-list/empty-collection/EmptyCollection.svelte
closes #677, for viewer member of team, + collection tooltip should be visible and plus icon be grayish
=> fix: tooltip-+collection-viewer [677]

src/packages/@app/pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts, src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte, src/packages/@workspaces/features/folder-explorer/layout/FolderExplorer.svelte
In this PR i have solved two issues on toast notification 
1.Added missing toast notification on changing folder name
2.Fixed  toast notification which appears twice  on changing the collection name . Changed it to one.
=> [staging] fix: Fixed multiple toast notification issue while renaming  [123]

src/packages/@app/pages/Help/HelpPage.svelte
The right click functionality on other pages except the help page was disabled. Used the 'contextmenu' event listener to fix it.
=> [staging] fix : disabled right click on help page to make it consistent  [123]

src/packages/@app/pages/Auth/login-page/login-page.ts
When new user sign up and logged in the sparrow for the first time. The first page showed before was new request page but now i have changed it to rest api page.
=> [staging] Fix/redirecting to rest api page

src/packages/@workspaces/features/import-collection/layout/ImportCollection.svelte
import collection validation issue in mac, added preetifier for JSON
=> fix: import collection validation issue in mac []

src/packages/@workspaces/features/collection-explorer/layout/CollectionExplorer.svelte
In this PR i have again fixed the z-index since the previous z index is overriding the pop up
=> [staging] fix: Fixed z index of Collection list[123]

src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte, src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
In this pr i have solved the save requestion button  function issue that is without changing the name of the request it called again on clicking the button and the toast appears
=> [staging] Fix: fixed request save btn function 

src/packages/@common/components/sidebar/SidebarProfileModal.svelte
This PR solved the issue when a  user takes his/her username too long than while hovering on profile button in siderbar the UI of profile detail box expand too long .
This PR has fixed this issue by giving max-width to the container
=> [staging] fix: Fixed overlapping username issue [123]

src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte, src/packages/@workspaces/features/collection-list/components/folder/Folder.svelte
I have fixed the issue while we click on input on renaming the environment name there is on blur event call which should not be call without any change so added a if condition that is previous value is equal to current value than there should not be any function call and also i have increase the gap between the folder name and shortcut button
=> [staging] Fix: Fixed Env renaming  function call [123]

src/packages/@app/pages/EnvironmentPage/EnvironmentPage.ViewModel.ts, src/packages/@app/pages/EnvironmentPage/EnvironmentPage.svelte, src/packages/@app/styles/style.scss, src/packages/@common/components/header/Header.svelte, src/packages/@common/components/sidebar/Sidebar.svelte, src/packages/@environments/common/components/tabular-input/TabularInput.svelte, src/packages/@environments/features/environment-explorer/layout/EnvironmentExplorer.svelte, src/packages/@environments/features/environment-list/components/list-item/ListItem.svelte, src/packages/@workspaces/common/components/tabular-input/TabularInput.svelte, src/packages/@workspaces/common/components/tabular-input/TabularInputFormData.svelte, src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte, src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte, src/packages/@workspaces/features/tab-bar/components/tab/Tab.svelte
=> fix: Color contrast implementation[123]

src/packages/@common/features/delete-workspace/layout/DeleteWorkspace.svelte, src/packages/@library/ui/icon-fallback/IconFallback.svelte, src/packages/@teams/features/team-invite/layout/TeamInvite.svelte, src/packages/@teams/features/team-members/components/member/Member.svelte
This pull request addresses the issue where the teams icon does not update when a role is changed from the dropdown menu in the Teams module.
Fixes #1233
=> Fix: Teams icon Update Issue on Role Change in Teams Module

src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts, src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.svelte, src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts, src/packages/@app/services/user.service.ts, src/packages/@teams/features/team-invite/layout/TeamInvite.svelte
This pull request introduces a feature to disable the invitation functionality for users who are already members of a team. This prevents sending redundant invites and improves the user experience by avoiding confusion and clutter.
Fixes #1234
=> Feat: disable invite for user already exist in team

src/packages/@teams/features/create-team/components/team-icon/TeamIcon.svelte, src/packages/@teams/features/team-settings/components/team-profile/sub-team-profile/update-team-icon/UpdateTeamIcon.svelte
#1226 
In this PR i have fixed the valdation issue realted to uploading the team icon as pdf .
The validation is not coming in mac when we are uploading the team image as pdf and also the app is getting crashed .
So what i have done is that  first understood the issue since the code is working in  windows but not woring in mac then what i found is that when we are uploading the team logo as pdf in mac then it is taking as  jpeg format and also the name of file is changed to  "tempImage"+"some random words"   , so for now what we have done is that , we have put a check that if the  operating system is Macos and  the file that is uploading included tempImage then it show that we are trying to upload the pdf from mac so now we thrwoing the same error that comes when we upload the pdf file . …
=> fix: Fixed the validation issue in mac [#1226]

src/packages/@workspaces/features/save-as-request/layout/SaveAsRequest.svelte
#1465 
In this Pr sovlve the ui overlapping issue in save request pop up
=> fix: fixed ui issue in save request popup[#1465]

src/packages/@app/pages/Collections/CollectionPage.ViewModel.ts, src/packages/@app/pages/TeamExplorerPage/TeamExplorerPage.ViewModel.ts, src/packages/@app/pages/WorkspaceExplorerPage/WorkspaceExplorerPage.ViewModel.ts, src/packages/@app/repositories/team.repository.ts, src/packages/@app/repositories/workspace.repository.ts, src/packages/@app/services/team.service.ts
This PR refactors the logic that handles the deletion of workspace items when a team member leaves. The goal is to remove functions coupling through multiple repositories.
=> refactor: delete workspace items operations on team leave

src/packages/@app/pages/RestExplorer/RestExplorerPage.ViewModel.ts, src/packages/@app/pages/RestExplorer/RestExplorerPage.svelte, src/packages/@deprecate/api/api.common.ts, src/packages/@workspaces/common/type/actions.ts, src/packages/@workspaces/features/rest-explorer/components/http-url-section/HttpUrlSection.svelte, src/packages/@workspaces/features/rest-explorer/layout/RestExplorer.svelte
A cancel button will appear once request is initiated before the response appears to cancel the ongoing request.
Request cancels just on the UI while it continues to execute in the background, this happens since it is a RPC call and not a JS call. This is not a blocker and can be taken up as a enhancement in a future iteration.
=> feat: Cancel request midway

.github/workflows/development.yaml
Reverts sparrowapp-dev/sparrow-app#1962
Reverting this PR as mac build is failing.
=> Revert "build: update development build yaml"

apps/@sparrow-web/index.html
This update introduces a 2-second delay before rendering the web application on initial load. The delay is intended to ensure that essential application data is fetched and available before the UI is displayed, enhancing user experience by providing a fully prepared state on render.
#1959
=> fix: delay web app render by 2 sec on load to fetch essential app data

apps/@sparrow-desktop/src-tauri/tauri.conf.json
This fixes the dmg installer size to rectify icon alignment issue in mac.
=> fix: mac dmg installer alignment

docs/CODE_PATTERNS.md
This PR introduces a comprehensive Coding Patterns and Guidelines document to ensure consistency, readability, and maintainability across the codebase.
- Standardized naming conventions for variables, functions, classes, and constants.
- Emphasis on best practices, including arrow functions, destructuring, and default parameters.
- Clear examples demonstrating preferred and non-preferred approaches.
- Principles like Single Responsibility and avoiding magic numbers.
- Improved error handling patterns.
- Enhances code clarity and reduces ambiguity.
- Encourages adherence to industry best practices.
- Serves as a reference guide for both new and existing developers.
- Please review the document and share your feedback! 🚀
=> Add Coding Patterns and Guidelines Documentation

packages/@sparrow-teams/src/features/team-explorer/components/workspace-grid-view/WorkspaceGridView.svelte
I have updated image size according to the Figma [#2364].
=> fix: updated UI image of sparrow edge in Teams

packages/@sparrow-workspaces/src/components/drop-button/DropButton.svelte
Run button icon and text is not properly aligned in webapp
[#2418](https://github.com/sparrowapp-dev/sparrow-app/issues/2418)
1.Open webapp
2.Go to test flow
3.Add block in it
Expected-
Run button and logo should be properly aligned
Actual-
It is not properly aligned
after changes the drop-button code we get
=> feat: Run button icon and text is not properly aligned in webapp #2418

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts, apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte, apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts, apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte, apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.svelte, apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.svelte, packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte, packages/@sparrow-workspaces/src/features/folder-explorer/layout/FolderExplorer.svelte
API Request Count 
[#2422](https://github.com/sparrowapp-dev/sparrow-app/issues/2422)
Description : The system should display a real-time count of the following items: Folders, REST API Requests, GraphQL Requests, WebSocket connections, and Socket.IO connections. These counts should update automatically whenever changes occur, ensuring that users always see the most accurate information.
Figma/SS:
Acceptance criteria 1: [Count update]
Given User wants to see the count of any of the mentioned aspects Folders, REST API Requests, GraphQL Requests, WebSocket connections, and Socket.IO connections.
When user creates or deletes any of these items in the application.
Then User should be able to see the count of each item should update automatically and reflect the current state.
after solving
=> fix : API Request Count

packages/@sparrow-library/src/ui/radio-button/RadioButton.svelte
I have fixed the circle issue in the Radio button on focus state.
=> fix: Focused state circle issue of radio button.

apps/@sparrow-web/src/containers/api/api.common.ts
Fixed the message typo in WebSocket connections notification.
**Suggestion:** We should store all the constant strings and values inside a constants file instead of hardcoding the values. It will be helpful for reuse.
=> fix: fixed the typos for notifications messages

packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
Fixed the count of blocks in the delete popup for block in testflows.
=> fix: fixed the wrong block count in the delete popup in testflows

packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte
I have removed the function call that was affecting the environment selection when the user clicked on the text div.
=> Fix: Environment should be de-selected once user check that radio button.

apps/@sparrow-desktop/src/components/styles.css, apps/@sparrow-web/src/components/styles.css, packages/@sparrow-common/src/constants/fonts.constant.ts, packages/@sparrow-library/src/ui/button/Button.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/collection/Collection.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/graphql/Graphql.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/request/Request.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/socket-io/SocketIo.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/web-socket/WebSocket.svelte, packages/@sparrow-workspaces/src/features/collection-list/layout/CollectionList.svelte, packages/@sparrow-workspaces/src/features/environment-list/components/list-item/ListItem.svelte, packages/@sparrow-workspaces/src/features/environment-list/layout/EnvironmentList.svelte, packages/@sparrow-workspaces/src/features/testflow-list/components/testflow-list-item/TestflowListItem.svelte, packages/@sparrow-workspaces/src/features/testflow-list/layout/TestflowList.svelte
Update app typography from Roboto to Inter; JetBrains for code editor. Adjusted side nav font weight to match Figma
This change is impplemented in 
issue: [#2839](https://github.com/sparrowapp-dev/sparrow-app/issues/2839)
after:
before:
=> fix: typography update

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte, apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerSavedPage/RestExplorerSavedPage.svelte, packages/@sparrow-common/src/features/create-team/components/team-description/TeamDescription.svelte, packages/@sparrow-library/src/forms/label-field/LabelField.svelte, packages/@sparrow-workspaces/src/components/codemirror-input/CodeMirrorInput.svelte, packages/@sparrow-workspaces/src/components/missed-environment/MissedEnvironment.svelte
This PR fixes an issue where the environment was missing for saved requests. The bug caused inconsistencies when loading or executing saved requests due to the absence of the expected environment data.
Changes
- Ensure the environment is properly assigned when saving requests.
- Add validation to prevent saving requests without an associated environment.
- Update relevant tests to cover the missing environment scenario.
=> fix: environment missing issue for saved request 

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte, apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
We are rolling back the changes for auto environment select feature. As this issue created inconsistent button states for environment dropdown and radio button selection. W'll fix it in upcoming days.
No issue raised for this, as this is a rollback pr
=> Rollback: rolling backing the changes for auto environment select

apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte, apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte
Truncating the tab name if too long 
Self Reported Bug
No Issue reported 
=> fix: Truncating the tab names if too long

packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte, packages/@sparrow-workspaces/src/features/collection-list/components/folder/Folder.svelte
bug 1 : When user create new collection, it should open in opened state instead of close state.(Same behaviour as folder)
bug 2 : From Edge, remove this recent workspace option, as it is not present in top.
- [*] **The pull request only addresses one issue or adds one feature.**
- [*] **I have linked an issue to the pull request.**
- [*] **I have linked a PR type label to the pull request.**
- [*] **The pull request does not introduce any breaking changes**
- [*] **I have added screenshots or gifs to help explain the change if applicable.**
- [*] **I have read the [contribution guidelines](../../docs/CONTRIBUTING.md).**
Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple …
=> fix : bugs solve in global Search and left panel workspace

packages/@sparrow-workspaces/src/features/socket-explorer/components/request-body/SocketMessage.svelte, packages/@sparrow-workspaces/src/features/socketio-explorer/components/request-body/RequestMessage.svelte
Disable clear input button when input is empty.
https://github.com/user-attachments/assets/6b136448-19c3-4b82-9d38-74d86fa51e63
=> fix: disable clear input CTA if editor is empty

packages/@sparrow-workspaces/src/components/tabular-input/TabularInput.svelte, packages/@sparrow-workspaces/src/components/tabular-input/TabularInputFormData.svelte
Fixed auto-scroll issue when adding key-value pairs in Params and Headers. It was working on Windows but not on macOS — now works consistently across both platforms.
Fixes #<[1518](https://github.com/sparrowapp-dev/sparrow-app/issues/1518)>
=> fix: auto-scroll issue on macOS when adding key-value pair

apps/@sparrow-web/src/pages/workspace-page/sub-pages/WebSocketExplorerPage/WebSocketExplorerPage.ViewModel.ts, packages/@sparrow-workspaces/src/features/collection-explorer/layout/CollectionExplorer.svelte, packages/@sparrow-workspaces/src/features/environment-explorer/layout/EnvironmentExplorer.svelte, packages/@sparrow-workspaces/src/features/socket-explorer/layout/SocketExplorer.svelte, packages/@sparrow-workspaces/src/features/socketio-explorer/layout/SocketIoExplorer.svelte, packages/@sparrow-workspaces/src/features/workspace-explorer/components/workspace-header/WorkspaceHeader.svelte
Resolved UX issue where the `Ctrl+S` / `Cmd+S` save shortcut did not trigger the save action across several sections including:
- Collection
- Workspace
- Environment
- WebSocket
- Socket.IO
https://github.com/user-attachments/assets/3b0158d4-d61c-46c7-b556-9c3ea13f2076
=> fix: save shortcuts on Collection, Workspace, Environment, WebSocket & Socket.IO

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorer/RestExplorerPage.ViewModel.ts, packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
Bug Fix:
1. Disabling the chat item like/dislike action buttons for desktop version
2. Refactored the quick help banner
=> fix: disable like dislike for empty messages

packages/@sparrow-workspaces/src/features/chat-bot/components/ai-chat-interface/AIChatInterface.svelte, packages/@sparrow-workspaces/src/features/chat-bot/components/chat-item/ChatItem.svelte
Extra space was coming on the right side of the code preview popup. Fixed by resizing the max-width. This issue was occurring in the larger screen sizes.
Before
After
=> fix: fixed extra spacing on preview code block

packages/@sparrow-workspaces/src/features/testflow-explorer/components/response-body-navigator/ResponseBodyNavigator.svelte
I have updated the gap between the response button's.
Fixes # SPRW-653
=> Fix: Testflow reponse button gap issue.

packages/@sparrow-workspaces/src/components/tabular-input/LazyElement.svelte, packages/@sparrow-workspaces/src/components/tabular-input/LazyElementFormData.svelte, packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/components/function-options/FunctionsOptions.svelte, packages/@sparrow-workspaces/src/features/testflow-dynamic-expressions/layout/TestflowDynamicExpression.svelte, packages/@sparrow-workspaces/src/features/testflow-explorer/layout/TestflowExplorer.svelte
I have fixed UI issues in the dynamic expression along with the location display feature.
Fixes # not available. 
1.It is solves the UI issue in parameter and header for empty values UI alignment. 
2.It solves the issue of the dynamic expression not being shown for the first item in the form data.
=> fix: testflow dynamic expression UI and functionality issues.

packages/@sparrow-teams/src/features/team-list/layout/TeamList.svelte, packages/@sparrow-teams/src/features/team-sidepanel/layout/TeamSidePanel.svelte
Fixed the sparrow hubs heading to "Hubs"
=> fix: fixed the hubs heading [SPRW-693]

packages/@sparrow-support/src/features/release-notes/layout/ReleaseNotes.svelte
The URL in releases in timeline section is now opening in web instead of desktop app.
=> fix: sparrow release timeline url

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts, apps/@sparrow-desktop/src/pages/teams-page/Teams.ViewModel.ts, apps/@sparrow-desktop/src/pages/workspace-page/CollectionsPage.svelte, apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts, apps/@sparrow-desktop/src/repositories/collection.repository.ts, apps/@sparrow-desktop/src/repositories/environment.repository.ts, apps/@sparrow-desktop/src/repositories/testflow.repository.ts, apps/@sparrow-desktop/src/repositories/workspace.repository.ts, apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts, apps/@sparrow-web/src/pages/Teams/Teams.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/CollectionsPage.svelte, apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts, apps/@sparrow-web/src/repositories/collection.repository.ts, apps/@sparrow-web/src/repositories/environment.repository.ts, apps/@sparrow-web/src/repositories/testflow.repository.ts, apps/@sparrow-web/src/repositories/workspace.repository.ts, packages/@sparrow-common/src/features/global-search/components/RecentItems/RecentItems.svelte
In these PR we have, 
FIxed the issue when mock api was opening as collection, 
Added removce environments, collections, and testflows with workspaceID function in repository so that when workspace is switched from public to private, the uncessary data of orphan workspaces could be removed. 
=> fix: restricted to open orphan data from global search [SPRW-1155]

packages/@sparrow-common/src/components/header/Header.svelte
Add spacing between profile icon and right boundary [SPRW-986].
[SPRW-986]: https://techdome.atlassian.net/browse/SPRW-986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add gap between profile icon and right boundary [SPRW-986]

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts, apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/CollectionExplorerPage/CollectionExplorerPage.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/FolderExplorerPage/FolderExplorerPage.ViewModel.ts
When creating mock request from collection page and folder page, base url was coming in path url part. 
Removed saving the mock base url in mock request url and replace it with empty string. 
=> fix: removed base url in tab creation []

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts, apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte, apps/@sparrow-desktop/src/repositories/collection.repository.ts, apps/@sparrow-desktop/src/services/collection.service.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/RestExplorerMockPage/RestExplorerMockPage.svelte, apps/@sparrow-web/src/repositories/collection.repository.ts, apps/@sparrow-web/src/services/collection.service.ts, packages/@sparrow-common/src/components/index.ts, packages/@sparrow-common/src/components/number-input/NumberInput.svelte, packages/@sparrow-common/src/types/workspace/http-response-mock-dto.ts, packages/@sparrow-library/src/forms/index.ts, packages/@sparrow-library/src/forms/number-input/NumberInput.svelte, packages/@sparrow-library/src/icons/DocumentPercentRegular.svelte, packages/@sparrow-library/src/icons/index.ts, packages/@sparrow-library/src/ui/index.ts, packages/@sparrow-library/src/ui/progress-bar/ProgressBar.svelte, packages/@sparrow-library/src/ui/progress-bar/index.ts, packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/index.ts, packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-response-state/MockResponseState.svelte, packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/mock-responses-ratio/MockResponsesRatio.svelte, packages/@sparrow-workspaces/src/features/rest-explorer-mock/components/multiple-mock-response/MultipleMockResponse.svelte, packages/@sparrow-workspaces/src/features/rest-explorer-mock/layout/RestExplorerMock.svelte
In this pr, I have added the functionality of setting the mock response ratio.
=> Add the functionality of response ratio

.github/workflows/sparrow-app-prod.yaml
This PR sets up the automated Linux release process 
- Builds the .deb package for Linux using Tauri and signs it with the project’s private key.
- Injects the production updater URL into tauri.conf.json using a GitHub Actions secret.
- Generates the required APT repo metadata files and signs them with GPG for secure distribution.
- Uploads the signed .deb package and repo metadata to an S3 bucket configured to serve as a Debian repository.
=> build: Add production release workflow

packages/@sparrow-library/src/forms/editor/Editor.svelte
App was freezing when a request body has window style space(\r\n) as body length was coming different when compared to it's beautified. 
To resolve this added a check to remove window style space from string. 
=> fix: added value length check in editort for window style space [SPRW-1622]

packages/@sparrow-workspaces/src/features/workspace-actions/layout/WorkspaceActions.svelte
fix: SPRW-1267-left-panel-workspace-name-has-space-but-its-being-truncated-to-early 
Fixes #1267 SPRW
=> fix: SPRW-1267-left-panel-workspace-name-has-space-but-its-being-truncated-to-early 

packages/@sparrow-workspaces/src/features/socketio-explorer/components/http-url-section/HttpUrlSection.svelte
I have added disabled state for the Socket IO connection so that user cannot update the input URL while connected to the Socket IO.
Fixes #jira
=> Fix: Input issue with Socket.IO during connection SPRW-1538.

apps/@sparrow-desktop/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts, apps/@sparrow-web/src/pages/workspace-page/sub-pages/EnvironmentExplorer/EnvironmentExplorerPage.ViewModel.ts, packages/@sparrow-workspaces/src/components/tabular-input-v2/TabularInputV2.svelte
I’ve resolved the "generate variable undo" issue. The problem occurred due to index changes when items were removed. To fix this, I introduced an undo property and ensured that both undo and id are passed into the keyValuePair. We now identify the correct keyValuePair based on its id.
Fixes #jira
=> fix: generate variable undo issue SPRW-1652. 

apps/@sparrow-desktop/src/pages/dashboard-page/Dashboard.ViewModel.ts, apps/@sparrow-web/src/pages/Dashboard/Dashboard.ViewModel.ts
I’ve updated the condition to handle cases where the updatedAt variable is missing. Previously, all items were assigned the latest timestamp, which broke the filtering logic.
Fixes #jira
https://github.com/user-attachments/assets/6dfa1e12-1d47-47c6-b7aa-dee37a67bfdd
=> fix: global search folder issue SPRW-1754.

packages/@sparrow-workspaces/src/features/rest-explorer/components/request-navigator/RequestNavigator.svelte, packages/@sparrow-workspaces/src/features/rest-explorer/layout/RestExplorer.svelte
I have condition to show the button only when headers or params are in normal mode. 
Fixes #jira
=> fix: mock data restrictions during bulk edit of headers and params SPRW-2022.
